from mara_host.command.client import MaraClient
from mara_host.core.event_bus import EventBus
from mara_host.core.host_module import CommandHostModule


class GpioHostModule(CommandHostModule):
    """GPIO write/read/toggle helpers.

    Wraps CMD_GPIO_WRITE / CMD_GPIO_READ / CMD_GPIO_TOGGLE
    using the generated cmd_gpio_* methods on MaraClient.
    """

    module_name = "gpio"

    def __init__(self, bus: EventBus, client: MaraClient) -> None:
        super().__init__(bus, client)

    async def write(self, channel: int, value: int) -> None:
        # Use autogenerated helper instead of hardcoding CMD_*:
        await self._client.cmd_gpio_write(
            channel=int(channel),
            value=int(value),
        )

    async def read(self, channel: int) -> None:
        # For now just send the command; higher-level code can listen
        # for the corresponding ACK on the EventBus.
        await self._client.cmd_gpio_read(
            channel=int(channel),
        )

    async def toggle(self, channel: int) -> None:
        await self._client.cmd_gpio_toggle(
            channel=int(channel),
        )
