from mara_host.command.client import MaraClient
from mara_host.core.event_bus import EventBus
from mara_host.core.host_module import CommandHostModule


class PwmHostModule(CommandHostModule):
    """PWM_SET helper.

    Wraps the autogenerated cmd_pwm_set() on MaraClient.
    """

    module_name = "pwm"

    def __init__(self, bus: EventBus, client: MaraClient) -> None:
        super().__init__(bus, client)

    async def set(self, channel: int, duty: float, freq_hz: float | None = None) -> None:
        # Use the generated helper so CMD_PWM_SET stays in the mixin.
        await self._client.cmd_pwm_set(
            channel=int(channel),
            duty=float(duty),
            freq_hz=float(freq_hz) if freq_hz is not None else None,
        )
