from robot_host.command.client import AsyncRobotClient
from robot_host.core.event_bus import EventBus
from robot_host.core.host_module import CommandHostModule


class ServoHostModule(CommandHostModule):
    """Servo attach/set helpers.

    Wraps the autogenerated cmd_servo_* methods on AsyncRobotClient.
    """

    module_name = "servo"

    def __init__(self, bus: EventBus, client: AsyncRobotClient) -> None:
        super().__init__(bus, client)

    async def attach(
        self,
        servo_id: int = 0,
        channel: int = 0,
        min_us: int = 500,
        max_us: int = 2500,
    ) -> None:
        # Note: cmd_servo_attach expects (servo_id, channel, min_us, max_us)
        await self._client.cmd_servo_attach(
            servo_id=int(servo_id),
            channel=int(channel),
            min_us=int(min_us),
            max_us=int(max_us),
        )

    async def set_angle(
        self,
        servo_id: int,
        angle_deg: float,
        duration_ms: int = 0,
    ) -> None:
        await self._client.cmd_servo_set_angle(
            servo_id=int(servo_id),
            angle_deg=float(angle_deg),
            duration_ms=int(duration_ms),
        )
