from robot_host.command.client import AsyncRobotClient
from robot_host.core.event_bus import EventBus
from robot_host.core.host_module import CommandHostModule


class StepperHostModule(CommandHostModule):
    """Stepper move/enable helpers.

    Wraps the autogenerated cmd_stepper_* methods on AsyncRobotClient.
    """

    module_name = "stepper"

    def __init__(self, bus: EventBus, client: AsyncRobotClient) -> None:
        super().__init__(bus, client)

    async def move_rel(self, motor_id: int, steps: int, speed_steps_s: float = 1000.0) -> None:
        await self._client.cmd_stepper_move_rel(
            motor_id=int(motor_id),
            steps=int(steps),
            speed_steps_s=float(speed_steps_s),
        )

    async def enable(self, motor_id: int, enable: bool = True) -> None:
        await self._client.cmd_stepper_enable(
            motor_id=int(motor_id),
            enable=bool(enable),
        )
