// include/sensor/AllSensors.h
// AUTO-GENERATED by scripts/generate_all_sensors.py
// DO NOT EDIT MANUALLY - changes will be overwritten
//
// To add a new sensor:
//   1. Create YourSensor.h implementing ISensor
//   2. Use REGISTER_SENSOR(YourSensor) macro
//   3. Rebuild - this file regenerates automatically

#pragma once

// Core infrastructure
#include "sensor/SensorRegistry.h"

// Auto-discovered self-registering sensors
#include "sensor/UltrasonicSensor.h"
