# mara_host/cli/commands/add.py
"""
Scaffolding command for adding new sensors and actuators.

Usage:
    mara add sensor temperature
    mara add actuator gripper
    mara add sensor pressure --bus i2c     # Complex I2C sensor (generates .h + .cpp)
    mara add sensor lidar --bus spi        # Complex SPI sensor (generates .h + .cpp)

Generates:
    - Firmware header implementing ISensor/IActuator (simple GPIO sensors)
    - OR Firmware header + cpp for Manager-style sensors (I2C/SPI)
    - Host service class with Config/State
    - Command payloads
    - Instructions for telemetry and MCP tools
"""

from __future__ import annotations

import re
from pathlib import Path
from datetime import datetime
from typing import Optional


# ═══════════════════════════════════════════════════════════════════════════
# Templates
# ═══════════════════════════════════════════════════════════════════════════

SENSOR_TEMPLATE = '''\
// include/sensor/{class_name}.h
// Self-registering {name} sensor
//
// Generated by: mara add sensor {name}
// Date: {date}

#pragma once

#include "config/FeatureFlags.h"

#if HAS_{feature_flag}

#include "sensor/ISensor.h"
#include "sensor/SensorMacros.h"
#include "config/PinConfig.h"
#include <Arduino.h>

namespace mara {{

class {class_name} : public ISensor {{
public:
    static constexpr const char* NAME = "{name}";
    static constexpr uint32_t DEFAULT_SAMPLE_INTERVAL_MS = 100;

    struct Reading {{
        float value = 0.0f;
        uint32_t lastSampleMs = 0;
        bool valid = false;
    }};

    // ISensor interface
    const char* name() const override {{ return NAME; }}

    uint32_t requiredCaps() const override {{
        return SensorCap::{cap_name};
    }}

    void init() override {{
        // TODO: Initialize hardware pins
        // Example:
        // pinMode(Pins::{pin_prefix}_DATA, INPUT);
        online_ = true;
    }}

    void loop(uint32_t now_ms) override {{
        if ((now_ms - reading_.lastSampleMs) < sampleIntervalMs_) {{
            return;
        }}

        // TODO: Read sensor value
        // reading_.value = readFromHardware();
        reading_.lastSampleMs = now_ms;
        reading_.valid = true;
    }}

    void toJson(JsonObject& out) const override {{
        out["value"] = reading_.value;
        out["valid"] = reading_.valid;
    }}

    // Public API
    float read() const {{ return reading_.value; }}
    bool isValid() const {{ return reading_.valid; }}

    void setSampleInterval(uint32_t ms) {{ sampleIntervalMs_ = ms; }}
    uint32_t getSampleInterval() const {{ return sampleIntervalMs_; }}

private:
    Reading reading_;
    uint32_t sampleIntervalMs_ = DEFAULT_SAMPLE_INTERVAL_MS;
}};

REGISTER_SENSOR({class_name});

}} // namespace mara

#else // !HAS_{feature_flag}

// Stub when disabled
namespace mara {{
class {class_name} {{
public:
    static constexpr const char* NAME = "{name}";
    float read() const {{ return 0.0f; }}
    bool isValid() const {{ return false; }}
}};
}}

#endif // HAS_{feature_flag}
'''

# ═══════════════════════════════════════════════════════════════════════════
# Complex Sensor Templates (I2C/SPI Manager pattern)
# ═══════════════════════════════════════════════════════════════════════════

SENSOR_MANAGER_HEADER_TEMPLATE = '''\
// include/sensor/{class_name}.h
// {title} sensor manager (I2C/SPI)
//
// Generated by: mara add sensor {name} --bus {bus}
// Date: {date}

#pragma once

#include "config/FeatureFlags.h"

#if HAS_{feature_flag}

#include "hal/I{bus_cap}.h"
#include "core/Debug.h"

// Forward declaration for auto-signals
class SignalBus;

class {class_name} {{
public:
    struct Sample {{
        float value = 0.0f;
        // TODO: Add fields for your sensor readings
    }};

    {class_name}() = default;

    /// Set the HAL {bus_upper} driver (must be called before begin)
    void setHal(hal::I{bus_cap}* {bus}) {{
        hal_ = {bus};
    }}

    /// Initialize sensor at given address.
    /// Returns true if device is detected and configured.
    bool begin(uint8_t addr = {default_addr});

    bool isOnline() const {{ return online_; }}
    uint8_t address() const {{ return addr_; }}
    hal::I{bus_cap}* hal() const {{ return hal_; }}

    /// Read one sample. Returns false if sensor offline or read failed.
    bool readSample(Sample& out);

    // -------------------------------------------------------------------------
    // Auto-Signals Support (optional)
    // -------------------------------------------------------------------------

    /// Enable auto-signal publishing to SignalBus.
    void enableAutoSignals(SignalBus* bus, uint16_t rate_hz = 100);

    /// Disable auto-signal publishing
    void disableAutoSignals();

    /// Check if auto-signals are enabled
    bool autoSignalsEnabled() const {{ return signals_ != nullptr; }}

    /// Publish current readings to SignalBus.
    void publishToSignals(uint32_t now_ms);

private:
    hal::I{bus_cap}* hal_ = nullptr;
    uint8_t addr_ = {default_addr};
    bool online_ = false;

    // Auto-signals state
    SignalBus* signals_ = nullptr;
    uint16_t signalRateHz_ = 100;
    uint32_t lastPublishMs_ = 0;
    bool signalsDefined_ = false;
}};

#else // !HAS_{feature_flag}

// Stub when disabled
class {class_name} {{
public:
    struct Sample {{
        float value = 0.0f;
    }};

    {class_name}() = default;
    void setHal(void*) {{}}
    bool begin(uint8_t = {default_addr}) {{ return false; }}
    bool isOnline() const {{ return false; }}
    uint8_t address() const {{ return {default_addr}; }}
    void* hal() const {{ return nullptr; }}
    bool readSample(Sample&) {{ return false; }}
    void enableAutoSignals(void*, uint16_t = 100) {{}}
    void disableAutoSignals() {{}}
    bool autoSignalsEnabled() const {{ return false; }}
    void publishToSignals(uint32_t) {{}}
}};

#endif // HAS_{feature_flag}
'''

SENSOR_MANAGER_CPP_TEMPLATE = '''\
// src/sensor/{class_name}.cpp
// {title} sensor manager implementation
//
// Generated by: mara add sensor {name} --bus {bus}
// Date: {date}

#include "config/FeatureFlags.h"

#if HAS_{feature_flag}

#include "sensor/{class_name}.h"
#include "control/SignalBus.h"
#include "core/Clock.h"

#include "config/PlatformConfig.h"
#if PLATFORM_HAS_ARDUINO
#include <Arduino.h>
#endif

namespace {{
// TODO: Define registers for your sensor
// Example for I2C sensor:
// static constexpr uint8_t REG_WHO_AM_I = 0x00;
// static constexpr uint8_t REG_CONFIG = 0x01;
// static constexpr uint8_t REG_DATA = 0x02;

// static constexpr uint8_t EXPECTED_WHO_AM_I = 0xXX;

bool writeChecked(hal::I{bus_cap}* hal, uint8_t addr, uint8_t reg, uint8_t value, const char* name) {{
    const hal::{bus_cap}Result result = hal->writeReg(addr, reg, value);
    if (result != hal::{bus_cap}Result::Ok) {{
        DBG_PRINTF("[{class_name}] Failed to write %s (0x%02X)\\n", name, reg);
        return false;
    }}
    return true;
}}
}} // namespace

bool {class_name}::begin(uint8_t addr) {{
    if (!hal_) {{
        DBG_PRINTLN("[{class_name}] begin() failed: HAL not set!");
        return false;
    }}

    online_ = false;
    addr_ = addr;
    DBG_PRINTF("[{class_name}] begin() addr=0x%02X\\n", addr_);

    // TODO: Check device presence
    // if (!hal_->devicePresent(addr_)) {{
    //     DBG_PRINTLN("[{class_name}] Device not found on bus");
    //     return false;
    // }}

    // TODO: Read WHO_AM_I register to verify device
    // uint8_t whoAmI = 0;
    // hal::{bus_cap}Result result = hal_->readReg(addr_, REG_WHO_AM_I, &whoAmI);
    // if (result != hal::{bus_cap}Result::Ok) {{
    //     DBG_PRINTLN("[{class_name}] Failed to read WHO_AM_I");
    //     return false;
    // }}
    // if (whoAmI != EXPECTED_WHO_AM_I) {{
    //     DBG_PRINTF("[{class_name}] Unexpected WHO_AM_I=0x%02X\\n", whoAmI);
    //     return false;
    // }}

    // TODO: Initialize sensor configuration
    // if (!writeChecked(hal_, addr_, REG_CONFIG, 0x00, "CONFIG")) {{
    //     return false;
    // }}

    mara::getSystemClock().delay(10);

    DBG_PRINTLN("[{class_name}] Sensor online and initialized");
    online_ = true;
    return true;
}}

bool {class_name}::readSample(Sample& out) {{
    if (!online_ || !hal_) {{
        return false;
    }}

    // TODO: Read raw data from sensor
    // uint8_t raw[2];
    // hal::{bus_cap}Result result = hal_->readRegs(addr_, REG_DATA, raw, sizeof(raw));
    // if (result != hal::{bus_cap}Result::Ok) {{
    //     DBG_PRINTLN("[{class_name}] readRegs failed");
    //     return false;
    // }}

    // TODO: Convert raw bytes to values
    // int16_t raw_value = (raw[0] << 8) | raw[1];
    // out.value = raw_value / 100.0f;

    out.value = 0.0f;  // Placeholder
    return true;
}}

// -----------------------------------------------------------------------------
// Auto-Signals Support
// -----------------------------------------------------------------------------

void {class_name}::enableAutoSignals(SignalBus* bus, uint16_t rate_hz) {{
    signals_ = bus;
    signalRateHz_ = rate_hz > 0 ? rate_hz : 100;
    lastPublishMs_ = 0;

    if (!bus || signalsDefined_) {{
        return;
    }}

    // TODO: Define auto-signals for your sensor readings
    // Use SignalNamespace constants from control/SignalBus.h
    // Example:
    // bus->defineAutoSignal(SignalNamespace::{feature_flag}_VALUE, "{name}.value", SignalBus::Kind::MEAS, 0.0f);

    signalsDefined_ = true;
    DBG_PRINTF("[{class_name}] Auto-signals enabled at %u Hz\\n", signalRateHz_);
}}

void {class_name}::disableAutoSignals() {{
    signals_ = nullptr;
    lastPublishMs_ = 0;
    DBG_PRINTLN("[{class_name}] Auto-signals disabled");
}}

void {class_name}::publishToSignals(uint32_t now_ms) {{
    if (!signals_ || !online_) {{
        return;
    }}

    // Rate limiting
    const uint32_t period_ms = signalRateHz_ > 0 ? (1000 / signalRateHz_) : 10;
    if (lastPublishMs_ > 0 && (now_ms - lastPublishMs_) < period_ms) {{
        return;
    }}

    Sample sample;
    if (!readSample(sample)) {{
        return;
    }}

    // TODO: Publish readings to signals
    // signals_->setAutoSignal(SignalNamespace::{feature_flag}_VALUE, sample.value, now_ms);

    lastPublishMs_ = now_ms;
}}

#endif // HAS_{feature_flag}
'''

ACTUATOR_TEMPLATE = '''\
// include/motor/{class_name}.h
// Self-registering {name} actuator
//
// Generated by: mara add actuator {name}
// Date: {date}

#pragma once

#include "config/FeatureFlags.h"

#if HAS_{feature_flag}

#include "motor/IActuator.h"
#include "motor/ActuatorRegistry.h"  // Contains REGISTER_ACTUATOR macro
#include "config/PinConfig.h"
#include "core/ServiceContext.h"
#include <Arduino.h>

namespace mara {{

class {class_name} : public IActuator {{
public:
    static constexpr const char* NAME = "{name}";

    // IActuator interface
    const char* name() const override {{ return NAME; }}

    uint32_t requiredCaps() const override {{
        return ActuatorCap::{cap_name};
    }}

    void init(ServiceContext& ctx) override {{
        // TODO: Store references to managers from context
        // gpio_ = ctx.gpio;
        // pwm_ = ctx.pwm;
        online_ = true;
    }}

    void setup() override {{
        // TODO: Configure pins and hardware
        // Example:
        // pinMode(Pins::{pin_prefix}_ENABLE, OUTPUT);
    }}

    void stopAll() override {{
        // TODO: Stop all outputs (called on ESTOP)
        // Example:
        // digitalWrite(Pins::{pin_prefix}_ENABLE, LOW);
    }}

    // Public API
    // TODO: Add actuator-specific methods
    // bool setPosition(float position);
    // float getPosition() const;

private:
    // TODO: Add state variables
    // GpioManager* gpio_ = nullptr;
    // PwmManager* pwm_ = nullptr;
}};

REGISTER_ACTUATOR({class_name});

}} // namespace mara

#else // !HAS_{feature_flag}

// Stub when disabled
namespace mara {{
class {class_name} {{
public:
    static constexpr const char* NAME = "{name}";
    void stopAll() {{}}
}};
}}

#endif // HAS_{feature_flag}
'''

SERVICE_TEMPLATE = '''\
# mara_host/services/control/{name}_service.py
"""
{title} service.

Generated by: mara add {kind} {name}
Date: {date}

Provides high-level control for {name} {kind}s.
"""

import asyncio
from dataclasses import dataclass
from typing import Optional, TYPE_CHECKING, Any

from mara_host.core.result import ServiceResult
from mara_host.services.control.service_base import ConfigurableService

if TYPE_CHECKING:
    from mara_host.command.client import MaraClient


@dataclass
class {class_name}Config:
    """Configuration for a {name} {kind}."""

    {kind}_id: int
    # TODO: Add configuration fields
    # pin: int = 0


@dataclass
class {class_name}State:
    """Current state of a {name} {kind}."""

    {kind}_id: int
    # TODO: Add state fields
    # value: Optional[float] = None
    attached: bool = False
    last_error: Optional[str] = None


class {class_name}Service(ConfigurableService[{class_name}Config, {class_name}State]):
    """
    Service for {name} {kind} control.

    Example:
        svc = {class_name}Service(client)

        # Attach {kind}
        await svc.attach(0)

        # Read value
        result = await svc.read(0)

        # Detach when done
        await svc.detach(0)
    """

    config_class = {class_name}Config
    state_class = {class_name}State
    id_field = "{kind}_id"

    def configure(
        self,
        {kind}_id: int,
        # TODO: Add configuration parameters
    ) -> {class_name}Config:
        """
        Configure a {name} {kind} locally.

        Args:
            {kind}_id: {title} ID

        Returns:
            {class_name}Config
        """
        config = {class_name}Config(
            {kind}_id={kind}_id,
        )
        self._configs[{kind}_id] = config
        return config

    async def attach(
        self,
        {kind}_id: int,
        # TODO: Add parameters
    ) -> ServiceResult:
        """
        Attach a {name} {kind}.

        Args:
            {kind}_id: {title} ID

        Returns:
            ServiceResult
        """
        # TODO: Implement attach command
        # payload = {class_name}AttachPayload({kind}_id={kind}_id)
        # ok, error = await self.client.send_reliable(payload._cmd, payload.to_dict())

        state = self.get_state({kind}_id)
        state.attached = True
        state.last_error = None
        return ServiceResult.success(data={{"{kind}_id": {kind}_id}})

    async def detach(self, {kind}_id: int) -> ServiceResult:
        """
        Detach a {name} {kind}.

        Args:
            {kind}_id: {title} ID

        Returns:
            ServiceResult
        """
        # TODO: Implement detach command

        state = self.get_state({kind}_id)
        state.attached = False
        state.last_error = None
        return ServiceResult.success(data={{"{kind}_id": {kind}_id}})

    async def read(self, {kind}_id: int) -> ServiceResult:
        """
        Read value from {name} {kind}.

        Args:
            {kind}_id: {title} ID

        Returns:
            ServiceResult
        """
        # TODO: Implement read command

        return ServiceResult.success(data={{
            "{kind}_id": {kind}_id,
            "value": 0.0,
        }})
'''


# ═══════════════════════════════════════════════════════════════════════════
# Generator
# ═══════════════════════════════════════════════════════════════════════════

def to_class_name(name: str) -> str:
    """Convert name to PascalCase class name."""
    # temperature -> Temperature
    # pressure_sensor -> PressureSensor
    parts = name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts)


def to_feature_flag(name: str) -> str:
    """Convert name to feature flag."""
    return name.upper().replace("-", "_")


def generate_sensor(
    name: str,
    output_dir: Path,
    firmware_dir: Path,
    bus: str = "gpio",
) -> list[Path]:
    """Generate sensor skeleton files.

    Args:
        name: Sensor name (e.g., "temperature")
        output_dir: Host mara_host directory
        firmware_dir: Firmware mcu directory
        bus: Bus type - "gpio" (header-only), "i2c" or "spi" (header + cpp)
    """
    created = []
    date = datetime.now().strftime("%Y-%m-%d")

    feature_flag = to_feature_flag(name)
    cap_name = feature_flag
    pin_prefix = feature_flag

    # Use Manager pattern for I2C/SPI sensors
    if bus in ("i2c", "spi"):
        class_name = to_class_name(name) + "Manager"
        return generate_complex_sensor(
            name=name,
            output_dir=output_dir,
            firmware_dir=firmware_dir,
            bus=bus,
        )

    # Simple GPIO sensor - header only
    class_name = to_class_name(name) + "Sensor"

    # Firmware sensor header
    firmware_file = firmware_dir / "include" / "sensor" / f"{class_name}.h"
    if not firmware_file.exists():
        firmware_file.parent.mkdir(parents=True, exist_ok=True)
        content = SENSOR_TEMPLATE.format(
            name=name,
            class_name=class_name,
            feature_flag=feature_flag,
            cap_name=cap_name,
            pin_prefix=pin_prefix,
            date=date,
        )
        firmware_file.write_text(content)
        created.append(firmware_file)

    # Host service
    service_name = to_class_name(name)
    service_file = output_dir / "services" / "control" / f"{name}_service.py"
    if not service_file.exists():
        service_file.parent.mkdir(parents=True, exist_ok=True)
        content = SERVICE_TEMPLATE.format(
            name=name,
            kind="sensor",
            title=service_name,
            class_name=service_name,
            date=date,
        )
        service_file.write_text(content)
        created.append(service_file)

    return created


def generate_complex_sensor(
    name: str,
    output_dir: Path,
    firmware_dir: Path,
    bus: str = "i2c",
) -> list[Path]:
    """Generate complex sensor with Manager pattern (I2C/SPI).

    Creates both header and cpp file like ImuManager pattern.
    """
    created = []
    date = datetime.now().strftime("%Y-%m-%d")

    class_name = to_class_name(name) + "Manager"
    feature_flag = to_feature_flag(name)
    title = to_class_name(name)

    # Bus-specific settings
    bus_cap = bus.upper() if bus == "spi" else "I2c"  # I2c vs SPI
    bus_upper = bus.upper()
    default_addr = "0x00" if bus == "spi" else "0x50"  # Typical I2C address

    # Firmware header
    header_file = firmware_dir / "include" / "sensor" / f"{class_name}.h"
    if not header_file.exists():
        header_file.parent.mkdir(parents=True, exist_ok=True)
        content = SENSOR_MANAGER_HEADER_TEMPLATE.format(
            name=name,
            class_name=class_name,
            feature_flag=feature_flag,
            title=title,
            bus=bus,
            bus_cap=bus_cap,
            bus_upper=bus_upper,
            default_addr=default_addr,
            date=date,
        )
        header_file.write_text(content)
        created.append(header_file)

    # Firmware cpp
    cpp_file = firmware_dir / "src" / "sensor" / f"{class_name}.cpp"
    if not cpp_file.exists():
        cpp_file.parent.mkdir(parents=True, exist_ok=True)
        content = SENSOR_MANAGER_CPP_TEMPLATE.format(
            name=name,
            class_name=class_name,
            feature_flag=feature_flag,
            title=title,
            bus=bus,
            bus_cap=bus_cap,
            bus_upper=bus_upper,
            default_addr=default_addr,
            date=date,
        )
        cpp_file.write_text(content)
        created.append(cpp_file)

    # Host service
    service_name = to_class_name(name)
    service_file = output_dir / "services" / "control" / f"{name}_service.py"
    if not service_file.exists():
        service_file.parent.mkdir(parents=True, exist_ok=True)
        content = SERVICE_TEMPLATE.format(
            name=name,
            kind="sensor",
            title=service_name,
            class_name=service_name,
            date=date,
        )
        service_file.write_text(content)
        created.append(service_file)

    return created


def generate_actuator(
    name: str,
    output_dir: Path,
    firmware_dir: Path,
) -> list[Path]:
    """Generate actuator skeleton files."""
    created = []
    date = datetime.now().strftime("%Y-%m-%d")

    class_name = to_class_name(name) + "Actuator"
    feature_flag = to_feature_flag(name)
    cap_name = feature_flag
    pin_prefix = feature_flag

    # Firmware actuator header
    firmware_file = firmware_dir / "include" / "motor" / f"{class_name}.h"
    if not firmware_file.exists():
        firmware_file.parent.mkdir(parents=True, exist_ok=True)
        content = ACTUATOR_TEMPLATE.format(
            name=name,
            class_name=class_name,
            feature_flag=feature_flag,
            cap_name=cap_name,
            pin_prefix=pin_prefix,
            date=date,
        )
        firmware_file.write_text(content)
        created.append(firmware_file)

    # Host service
    service_name = to_class_name(name)
    service_file = output_dir / "services" / "control" / f"{name}_service.py"
    if not service_file.exists():
        service_file.parent.mkdir(parents=True, exist_ok=True)
        content = SERVICE_TEMPLATE.format(
            name=name,
            kind="actuator",
            title=service_name,
            class_name=service_name,
            date=date,
        )
        service_file.write_text(content)
        created.append(service_file)

    return created


def find_build_yaml(project_root: Path) -> Path | None:
    """Find mara_build.yaml in the project."""
    # Check config/ directory first
    build_yaml = project_root / "config" / "mara_build.yaml"
    if build_yaml.exists():
        return build_yaml
    # Fallback to firmware/mcu/
    build_yaml = project_root / "firmware" / "mcu" / "mara_build.yaml"
    if build_yaml.exists():
        return build_yaml
    return None


def update_build_yaml(build_yaml: Path, kind: str, feature_name: str) -> bool:
    """
    Add feature to mara_build.yaml categories and profiles.

    Args:
        build_yaml: Path to mara_build.yaml
        kind: "sensor" or "actuator"
        feature_name: lowercase feature name (e.g., "temperature")

    Returns True if file was updated.
    """
    content = build_yaml.read_text()

    # Check if feature already exists
    if feature_name in content:
        return False

    lines = content.split("\n")
    new_lines = []

    # Determine which category to add to
    category = "Sensors" if kind == "sensor" else "Motors"

    # State machine for parsing
    in_categories = False
    in_target_category = False
    in_profiles = False
    current_profile = None
    category_indent = 0
    added_to_category = False
    profiles_updated = []

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Track sections
        if stripped == "categories:":
            in_categories = True
            in_profiles = False
        elif stripped == "profiles:":
            in_categories = False
            in_profiles = True

        # In categories section - find our target category
        if in_categories and stripped == f"{category}:":
            in_target_category = True
            category_indent = len(line) - len(line.lstrip())
            new_lines.append(line)
            i += 1
            # Add entries until we hit the next category or end
            while i < len(lines):
                entry_line = lines[i]
                entry_stripped = entry_line.strip()
                entry_indent = len(entry_line) - len(entry_line.lstrip())

                # Check if we've left this category
                if entry_stripped and not entry_stripped.startswith("-") and not entry_stripped.startswith("#"):
                    if entry_indent <= category_indent:
                        # Insert new feature before leaving category
                        if not added_to_category:
                            new_lines.append(f"{'  ' * (category_indent // 2 + 1)}- {feature_name}")
                            added_to_category = True
                        break

                new_lines.append(entry_line)

                # If this is the last entry in category, add after it
                if entry_stripped.startswith("-"):
                    # Peek ahead
                    if i + 1 < len(lines):
                        next_stripped = lines[i + 1].strip()
                        next_indent = len(lines[i + 1]) - len(lines[i + 1].lstrip())
                        if next_stripped and not next_stripped.startswith("-") and not next_stripped.startswith("#"):
                            if next_indent <= category_indent and not added_to_category:
                                new_lines.append(f"{'  ' * (category_indent // 2 + 1)}- {feature_name}")
                                added_to_category = True
                i += 1
            in_target_category = False
            continue

        # In profiles section - add to each profile's Sensors/Motors section
        if in_profiles:
            # Detect profile headers (e.g., "  minimal:")
            if stripped.endswith(":") and not stripped.startswith("#") and ":" not in stripped[:-1]:
                indent = len(line) - len(line.lstrip())
                if indent == 2:  # Profile level indent
                    current_profile = stripped[:-1]

            # Detect section comments (e.g., "# Sensors")
            if current_profile and stripped.lower() == f"# {category.lower()}":
                new_lines.append(line)
                i += 1
                # Add entries until next section
                while i < len(lines):
                    entry_line = lines[i]
                    entry_stripped = entry_line.strip()

                    # Check if we've hit the next section comment or left profile
                    if entry_stripped.startswith("#") and entry_stripped != f"# {category.lower()}":
                        # Insert before this comment
                        new_lines.append(f"    {feature_name}: false")
                        profiles_updated.append(current_profile)
                        break
                    elif not entry_stripped:
                        # Empty line might mean end of section
                        pass
                    elif ":" in entry_stripped and not entry_stripped.startswith("#"):
                        # This is a feature entry, keep going
                        pass
                    else:
                        break

                    new_lines.append(entry_line)
                    i += 1
                continue

        new_lines.append(line)
        i += 1

    if added_to_category or profiles_updated:
        build_yaml.write_text("\n".join(new_lines))
        return True

    return False


def print_next_steps(
    kind: str,
    name: str,
    created: list[Path],
    build_yaml_path: Path | None,
    yaml_updated: bool,
    bus: str = "gpio",
) -> None:
    """Print next steps for completing the integration."""
    class_name = to_class_name(name)
    feature_flag = to_feature_flag(name)
    is_complex = bus in ("i2c", "spi")

    print(f"\nCreated {len(created)} files:")
    for f in created:
        print(f"  {f}")

    print(f"\n{'='*60}")
    print("NEXT STEPS")
    print("="*60)

    step = 1

    # If YAML was updated, just tell them to enable it
    if yaml_updated:
        print(f"\n{step}. Enable the feature in mara_build.yaml:")
        print(f"   Set '{name}: true' in the profiles you want to use")
        step += 1
    elif build_yaml_path:
        print(f"\n{step}. Add feature flag to profiles in:")
        print(f"   {build_yaml_path}")
        print(f"   Under each profile, add:")
        print(f"     {name}: true")
        step += 1
    else:
        print(f"\n{step}. Add feature flag {name}: true to your build config")
        step += 1

    # Complex sensors (Manager pattern) need different instructions
    if is_complex and kind == "sensor":
        print(f"\n{step}. Implement the sensor protocol in {class_name}Manager.cpp:")
        print(f"   - Add register definitions for your sensor")
        print(f"   - Implement begin() with device detection and initialization")
        print(f"   - Implement readSample() to read and convert raw data")
        step += 1

        print(f"\n{step}. Add HAL setup in SetupSensors.cpp:")
        print(f"   - Create {class_name}Manager instance")
        print(f"   - Call setHal() with the {bus.upper()} interface")
        print(f"   - Call begin() with the device address")
        step += 1

        print(f"\n{step}. Add auto-signals (optional):")
        print(f"   In control/SignalBus.h, add to SignalNamespace:")
        print(f"   static constexpr uint16_t {feature_flag}_VALUE = 10XX;")
        print(f"   Then uncomment the defineAutoSignal/setAutoSignal calls")
        step += 1
    else:
        print(f"\n{step}. Add capability constant:")
        if kind == "sensor":
            print(f"   In ISensor.h, add to SensorCap namespace:")
            print(f"   constexpr uint32_t {feature_flag} = (1 << N);")
        else:
            print(f"   In IActuator.h, add to ActuatorCap namespace:")
            print(f"   constexpr uint32_t {feature_flag} = (1 << N);")
        step += 1

    print(f"\n{step}. Add command definitions:")
    print(f"   In CommandDefs.h, add:")
    print(f"   CMD_{feature_flag}_ATTACH,")
    print(f"   CMD_{feature_flag}_DETACH,")
    print(f"   CMD_{feature_flag}_READ,")
    step += 1

    print(f"\n{step}. Add telemetry provider (optional):")
    print(f"   In SetupTelemetry.cpp:")
    mgr_suffix = "Manager" if is_complex else "Sensor"
    print(f'   ctx.telemetry->registerProvider("{name}", [{name}{mgr_suffix}](...) {{ ... }});')
    step += 1

    print(f"\n{step}. Add MCP tools (optional):")
    print(f"   In mara_host/mcp/categories.py, add tool mappings")
    print(f"   Or create a plugin in ~/.mara/plugins/{name}_tools.py")
    step += 1

    print(f"\n{step}. Rebuild firmware:")
    print(f"   cd firmware/mcu && pio run")
    if not is_complex and kind == "sensor":
        print(f"\n   AllSensors.h will auto-regenerate on build.")
    elif kind == "actuator":
        print(f"\n   AllActuators.h will auto-regenerate on build.")


def run_add_command(args) -> int:
    """Run the add command."""
    kind = args.kind
    name = args.name.lower().replace("-", "_")
    bus = getattr(args, "bus", "gpio") or "gpio"

    # Find project directories
    # Assume we're running from host/ or the project root
    cwd = Path.cwd()

    # Try to find host dir
    if (cwd / "mara_host").exists():
        host_dir = cwd / "mara_host"
    elif (cwd / "host" / "mara_host").exists():
        host_dir = cwd / "host" / "mara_host"
    else:
        print("Error: Cannot find mara_host directory")
        print("Run this command from the host/ or project root directory")
        return 1

    # Try to find firmware dir
    if (cwd / "firmware" / "mcu").exists():
        firmware_dir = cwd / "firmware" / "mcu"
    elif (cwd.parent / "firmware" / "mcu").exists():
        firmware_dir = cwd.parent / "firmware" / "mcu"
    else:
        print("Warning: Cannot find firmware/mcu directory")
        print("Firmware files will not be generated")
        firmware_dir = None

    bus_info = f" (bus: {bus})" if bus != "gpio" else ""
    print(f"Adding {kind}: {name}{bus_info}")
    print(f"Host dir: {host_dir}")
    if firmware_dir:
        print(f"Firmware dir: {firmware_dir}")

    if kind == "sensor":
        created = generate_sensor(name, host_dir, firmware_dir, bus=bus)
    elif kind == "actuator":
        created = generate_actuator(name, host_dir, firmware_dir)
    else:
        print(f"Unknown kind: {kind}")
        return 1

    if not created:
        print("No files created (files may already exist)")
        return 0

    # Find and update mara_build.yaml
    # Project root is parent of firmware/mcu
    project_root = firmware_dir.parent.parent if firmware_dir else cwd
    build_yaml_path = find_build_yaml(project_root)

    yaml_updated = False
    if build_yaml_path:
        yaml_updated = update_build_yaml(build_yaml_path, kind, name)
        if yaml_updated:
            print(f"\nUpdated {build_yaml_path}")
            print(f"  Added '{name}' to categories and profiles (disabled by default)")

    print_next_steps(kind, name, created, build_yaml_path, yaml_updated, bus=bus)
    return 0


def register(subparsers):
    """Register the add command (auto-discovered by CLI)."""
    parser = subparsers.add_parser(
        "add",
        help="Scaffold new sensors or actuators",
        description="Generate skeleton files for new hardware components",
        epilog="""
Examples:
  mara add sensor temperature           # Simple GPIO sensor (header only)
  mara add sensor pressure --bus i2c    # I2C sensor (header + cpp, Manager pattern)
  mara add sensor lidar --bus spi       # SPI sensor (header + cpp, Manager pattern)
  mara add actuator gripper             # Create gripper actuator skeleton

Bus types:
  gpio (default): Simple GPIO-based sensor, header-only like UltrasonicSensor
  i2c:            I2C sensor with register access, generates .h + .cpp like ImuManager
  spi:            SPI sensor with register access, generates .h + .cpp like ImuManager
""",
    )
    parser.add_argument(
        "kind",
        choices=["sensor", "actuator"],
        help="Type of component to add",
    )
    parser.add_argument(
        "name",
        help="Name of the component (e.g., temperature, gripper)",
    )
    parser.add_argument(
        "--bus",
        choices=["gpio", "i2c", "spi"],
        default="gpio",
        help="Bus type for sensors: gpio (header-only), i2c/spi (header + cpp Manager pattern)",
    )
    parser.set_defaults(func=run_add_command)
    return parser
