# mara_host/cli/commands/add.py
"""
Scaffolding command for adding new sensors and actuators.

Usage:
    mara add sensor temperature
    mara add actuator gripper
    mara add sensor pressure --pins trig=12,echo=14

Generates:
    - Firmware header implementing ISensor/IActuator
    - Host service class with Config/State
    - Command payloads
    - Instructions for telemetry and MCP tools
"""

from __future__ import annotations

import re
from pathlib import Path
from datetime import datetime
from typing import Optional


# ═══════════════════════════════════════════════════════════════════════════
# Templates
# ═══════════════════════════════════════════════════════════════════════════

SENSOR_TEMPLATE = '''\
// include/sensor/{class_name}.h
// Self-registering {name} sensor
//
// Generated by: mara add sensor {name}
// Date: {date}

#pragma once

#include "config/FeatureFlags.h"

#if HAS_{feature_flag}

#include "sensor/ISensor.h"
#include "sensor/SensorMacros.h"
#include "config/PinConfig.h"
#include <Arduino.h>

namespace mara {{

class {class_name} : public ISensor {{
public:
    static constexpr const char* NAME = "{name}";
    static constexpr uint32_t DEFAULT_SAMPLE_INTERVAL_MS = 100;

    struct Reading {{
        float value = 0.0f;
        uint32_t lastSampleMs = 0;
        bool valid = false;
    }};

    // ISensor interface
    const char* name() const override {{ return NAME; }}

    uint32_t requiredCaps() const override {{
        return SensorCap::{cap_name};
    }}

    void init() override {{
        // TODO: Initialize hardware pins
        // Example:
        // pinMode(Pins::{pin_prefix}_DATA, INPUT);
        online_ = true;
    }}

    void loop(uint32_t now_ms) override {{
        if ((now_ms - reading_.lastSampleMs) < sampleIntervalMs_) {{
            return;
        }}

        // TODO: Read sensor value
        // reading_.value = readFromHardware();
        reading_.lastSampleMs = now_ms;
        reading_.valid = true;
    }}

    void toJson(JsonObject& out) const override {{
        out["value"] = reading_.value;
        out["valid"] = reading_.valid;
    }}

    // Public API
    float read() const {{ return reading_.value; }}
    bool isValid() const {{ return reading_.valid; }}

    void setSampleInterval(uint32_t ms) {{ sampleIntervalMs_ = ms; }}
    uint32_t getSampleInterval() const {{ return sampleIntervalMs_; }}

private:
    Reading reading_;
    uint32_t sampleIntervalMs_ = DEFAULT_SAMPLE_INTERVAL_MS;
}};

REGISTER_SENSOR({class_name});

}} // namespace mara

#else // !HAS_{feature_flag}

// Stub when disabled
namespace mara {{
class {class_name} {{
public:
    static constexpr const char* NAME = "{name}";
    float read() const {{ return 0.0f; }}
    bool isValid() const {{ return false; }}
}};
}}

#endif // HAS_{feature_flag}
'''

ACTUATOR_TEMPLATE = '''\
// include/motor/{class_name}.h
// Self-registering {name} actuator
//
// Generated by: mara add actuator {name}
// Date: {date}

#pragma once

#include "config/FeatureFlags.h"

#if HAS_{feature_flag}

#include "motor/IActuator.h"
#include "motor/ActuatorMacros.h"
#include "config/PinConfig.h"
#include "core/ServiceContext.h"
#include <Arduino.h>

namespace mara {{

class {class_name} : public IActuator {{
public:
    static constexpr const char* NAME = "{name}";

    // IActuator interface
    const char* name() const override {{ return NAME; }}

    uint32_t requiredCaps() const override {{
        return ActuatorCap::{cap_name};
    }}

    void init(ServiceContext& ctx) override {{
        // TODO: Store references to managers from context
        // gpio_ = ctx.gpio;
        // pwm_ = ctx.pwm;
        online_ = true;
    }}

    void setup() override {{
        // TODO: Configure pins and hardware
        // Example:
        // pinMode(Pins::{pin_prefix}_ENABLE, OUTPUT);
    }}

    void stopAll() override {{
        // TODO: Stop all outputs (called on ESTOP)
        // Example:
        // digitalWrite(Pins::{pin_prefix}_ENABLE, LOW);
    }}

    // Public API
    // TODO: Add actuator-specific methods
    // bool setPosition(float position);
    // float getPosition() const;

private:
    // TODO: Add state variables
    // GpioManager* gpio_ = nullptr;
    // PwmManager* pwm_ = nullptr;
}};

REGISTER_ACTUATOR({class_name});

}} // namespace mara

#else // !HAS_{feature_flag}

// Stub when disabled
namespace mara {{
class {class_name} {{
public:
    static constexpr const char* NAME = "{name}";
    void stopAll() {{}}
}};
}}

#endif // HAS_{feature_flag}
'''

SERVICE_TEMPLATE = '''\
# mara_host/services/control/{name}_service.py
"""
{title} service.

Generated by: mara add {kind} {name}
Date: {date}

Provides high-level control for {name} {kind}s.
"""

import asyncio
from dataclasses import dataclass
from typing import Optional, TYPE_CHECKING, Any

from mara_host.core.result import ServiceResult
from mara_host.services.control.service_base import ConfigurableService

if TYPE_CHECKING:
    from mara_host.command.client import MaraClient


@dataclass
class {class_name}Config:
    """Configuration for a {name} {kind}."""

    {kind}_id: int
    # TODO: Add configuration fields
    # pin: int = 0


@dataclass
class {class_name}State:
    """Current state of a {name} {kind}."""

    {kind}_id: int
    # TODO: Add state fields
    # value: Optional[float] = None
    attached: bool = False
    last_error: Optional[str] = None


class {class_name}Service(ConfigurableService[{class_name}Config, {class_name}State]):
    """
    Service for {name} {kind} control.

    Example:
        svc = {class_name}Service(client)

        # Attach {kind}
        await svc.attach(0)

        # Read value
        result = await svc.read(0)

        # Detach when done
        await svc.detach(0)
    """

    config_class = {class_name}Config
    state_class = {class_name}State
    id_field = "{kind}_id"

    def configure(
        self,
        {kind}_id: int,
        # TODO: Add configuration parameters
    ) -> {class_name}Config:
        """
        Configure a {name} {kind} locally.

        Args:
            {kind}_id: {title} ID

        Returns:
            {class_name}Config
        """
        config = {class_name}Config(
            {kind}_id={kind}_id,
        )
        self._configs[{kind}_id] = config
        return config

    async def attach(
        self,
        {kind}_id: int,
        # TODO: Add parameters
    ) -> ServiceResult:
        """
        Attach a {name} {kind}.

        Args:
            {kind}_id: {title} ID

        Returns:
            ServiceResult
        """
        # TODO: Implement attach command
        # payload = {class_name}AttachPayload({kind}_id={kind}_id)
        # ok, error = await self.client.send_reliable(payload._cmd, payload.to_dict())

        state = self.get_state({kind}_id)
        state.attached = True
        state.last_error = None
        return ServiceResult.success(data={{"{kind}_id": {kind}_id}})

    async def detach(self, {kind}_id: int) -> ServiceResult:
        """
        Detach a {name} {kind}.

        Args:
            {kind}_id: {title} ID

        Returns:
            ServiceResult
        """
        # TODO: Implement detach command

        state = self.get_state({kind}_id)
        state.attached = False
        state.last_error = None
        return ServiceResult.success(data={{"{kind}_id": {kind}_id}})

    async def read(self, {kind}_id: int) -> ServiceResult:
        """
        Read value from {name} {kind}.

        Args:
            {kind}_id: {title} ID

        Returns:
            ServiceResult
        """
        # TODO: Implement read command

        return ServiceResult.success(data={{
            "{kind}_id": {kind}_id,
            "value": 0.0,
        }})
'''


# ═══════════════════════════════════════════════════════════════════════════
# Generator
# ═══════════════════════════════════════════════════════════════════════════

def to_class_name(name: str) -> str:
    """Convert name to PascalCase class name."""
    # temperature -> Temperature
    # pressure_sensor -> PressureSensor
    parts = name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts)


def to_feature_flag(name: str) -> str:
    """Convert name to feature flag."""
    return name.upper().replace("-", "_")


def generate_sensor(
    name: str,
    output_dir: Path,
    firmware_dir: Path,
) -> list[Path]:
    """Generate sensor skeleton files."""
    created = []
    date = datetime.now().strftime("%Y-%m-%d")

    class_name = to_class_name(name) + "Sensor"
    feature_flag = to_feature_flag(name)
    cap_name = feature_flag
    pin_prefix = feature_flag

    # Firmware sensor header
    firmware_file = firmware_dir / "include" / "sensor" / f"{class_name}.h"
    if not firmware_file.exists():
        firmware_file.parent.mkdir(parents=True, exist_ok=True)
        content = SENSOR_TEMPLATE.format(
            name=name,
            class_name=class_name,
            feature_flag=feature_flag,
            cap_name=cap_name,
            pin_prefix=pin_prefix,
            date=date,
        )
        firmware_file.write_text(content)
        created.append(firmware_file)

    # Host service
    service_name = to_class_name(name)
    service_file = output_dir / "services" / "control" / f"{name}_service.py"
    if not service_file.exists():
        service_file.parent.mkdir(parents=True, exist_ok=True)
        content = SERVICE_TEMPLATE.format(
            name=name,
            kind="sensor",
            title=service_name,
            class_name=service_name,
            date=date,
        )
        service_file.write_text(content)
        created.append(service_file)

    return created


def generate_actuator(
    name: str,
    output_dir: Path,
    firmware_dir: Path,
) -> list[Path]:
    """Generate actuator skeleton files."""
    created = []
    date = datetime.now().strftime("%Y-%m-%d")

    class_name = to_class_name(name) + "Actuator"
    feature_flag = to_feature_flag(name)
    cap_name = feature_flag
    pin_prefix = feature_flag

    # Firmware actuator header
    firmware_file = firmware_dir / "include" / "motor" / f"{class_name}.h"
    if not firmware_file.exists():
        firmware_file.parent.mkdir(parents=True, exist_ok=True)
        content = ACTUATOR_TEMPLATE.format(
            name=name,
            class_name=class_name,
            feature_flag=feature_flag,
            cap_name=cap_name,
            pin_prefix=pin_prefix,
            date=date,
        )
        firmware_file.write_text(content)
        created.append(firmware_file)

    # Host service
    service_name = to_class_name(name)
    service_file = output_dir / "services" / "control" / f"{name}_service.py"
    if not service_file.exists():
        service_file.parent.mkdir(parents=True, exist_ok=True)
        content = SERVICE_TEMPLATE.format(
            name=name,
            kind="actuator",
            title=service_name,
            class_name=service_name,
            date=date,
        )
        service_file.write_text(content)
        created.append(service_file)

    return created


def print_next_steps(kind: str, name: str, created: list[Path]) -> None:
    """Print next steps for completing the integration."""
    class_name = to_class_name(name)
    feature_flag = to_feature_flag(name)

    print(f"\nCreated {len(created)} files:")
    for f in created:
        print(f"  {f}")

    print(f"\n{'='*60}")
    print("NEXT STEPS")
    print("="*60)

    print(f"\n1. Add feature flag to mara_build.yaml:")
    print(f"   features:")
    print(f"     {feature_flag}: true")

    print(f"\n2. Add capability constant:")
    if kind == "sensor":
        print(f"   In ISensor.h, add to SensorCap namespace:")
        print(f"   constexpr uint32_t {feature_flag} = (1 << N);")
    else:
        print(f"   In IActuator.h, add to ActuatorCap namespace:")
        print(f"   constexpr uint32_t {feature_flag} = (1 << N);")

    print(f"\n3. Add command definitions:")
    print(f"   In CommandDefs.h, add:")
    print(f"   CMD_{feature_flag}_ATTACH,")
    print(f"   CMD_{feature_flag}_DETACH,")
    print(f"   CMD_{feature_flag}_READ,")

    print(f"\n4. Add telemetry provider (optional):")
    print(f"   In SetupTelemetry.cpp:")
    print(f'   ctx.telemetry->registerProvider("{name}", [{name}Mgr](...) {{ ... }});')

    print(f"\n5. Add MCP tools (optional):")
    print(f"   In mara_host/mcp/categories.py, add tool mappings")
    print(f"   Or create a plugin in ~/.mara/plugins/{name}_tools.py")

    print(f"\n6. Rebuild firmware:")
    print(f"   cd firmware/mcu && pio run")
    print(f"\n   AllSensors.h will auto-regenerate on build.")


def run_add_command(args) -> int:
    """Run the add command."""
    kind = args.kind
    name = args.name.lower().replace("-", "_")

    # Find project directories
    # Assume we're running from host/ or the project root
    cwd = Path.cwd()

    # Try to find host dir
    if (cwd / "mara_host").exists():
        host_dir = cwd / "mara_host"
    elif (cwd / "host" / "mara_host").exists():
        host_dir = cwd / "host" / "mara_host"
    else:
        print("Error: Cannot find mara_host directory")
        print("Run this command from the host/ or project root directory")
        return 1

    # Try to find firmware dir
    if (cwd / "firmware" / "mcu").exists():
        firmware_dir = cwd / "firmware" / "mcu"
    elif (cwd.parent / "firmware" / "mcu").exists():
        firmware_dir = cwd.parent / "firmware" / "mcu"
    else:
        print("Warning: Cannot find firmware/mcu directory")
        print("Firmware files will not be generated")
        firmware_dir = None

    print(f"Adding {kind}: {name}")
    print(f"Host dir: {host_dir}")
    if firmware_dir:
        print(f"Firmware dir: {firmware_dir}")

    if kind == "sensor":
        created = generate_sensor(name, host_dir, firmware_dir)
    elif kind == "actuator":
        created = generate_actuator(name, host_dir, firmware_dir)
    else:
        print(f"Unknown kind: {kind}")
        return 1

    if not created:
        print("No files created (files may already exist)")
        return 0

    print_next_steps(kind, name, created)
    return 0


def register(subparsers):
    """Register the add command (auto-discovered by CLI)."""
    parser = subparsers.add_parser(
        "add",
        help="Scaffold new sensors or actuators",
        description="Generate skeleton files for new hardware components",
        epilog="""
Examples:
  mara add sensor temperature    # Create temperature sensor skeleton
  mara add actuator gripper      # Create gripper actuator skeleton
""",
    )
    parser.add_argument(
        "kind",
        choices=["sensor", "actuator"],
        help="Type of component to add",
    )
    parser.add_argument(
        "name",
        help="Name of the component (e.g., temperature, gripper)",
    )
    parser.set_defaults(func=run_add_command)
    return parser
