#!/usr/bin/env python3
"""
Pre-build script to auto-generate AllSensors.h

Scans for *Sensor.h files that contain REGISTER_SENSOR and generates
the include list. This enables 1-file sensor extensibility.

Usage:
  PlatformIO pre-build hook (see extra_scripts in platformio.ini)
  OR manual: python scripts/generate_all_sensors.py
"""

import inspect
import re
from pathlib import Path


def _resolve_script_path() -> Path:
    """Resolve this script path even when PlatformIO/SCons omits __file__."""
    file_value = globals().get("__file__")
    if file_value:
        return Path(file_value).resolve()

    source_file = inspect.getsourcefile(lambda: None) or inspect.getfile(lambda: None)
    if source_file and source_file != "<string>":
        return Path(source_file).resolve()

    candidate = (Path.cwd() / "scripts" / "generate_all_sensors.py").resolve()
    if candidate.exists():
        return candidate

    raise RuntimeError("Unable to resolve generate_all_sensors.py path")


SCRIPT_PATH = _resolve_script_path()
SENSOR_DIR = SCRIPT_PATH.parent.parent / "include" / "sensor"
OUTPUT_FILE = SENSOR_DIR / "AllSensors.h"

HEADER_TEMPLATE = """\
// include/sensor/AllSensors.h
// AUTO-GENERATED by scripts/generate_all_sensors.py
// DO NOT EDIT MANUALLY - changes will be overwritten
//
// To add a new sensor:
//   1. Create YourSensor.h implementing ISensor
//   2. Use REGISTER_SENSOR(YourSensor) macro
//   3. Rebuild - this file regenerates automatically

#pragma once

// Core infrastructure
#include "sensor/SensorRegistry.h"

// Auto-discovered self-registering sensors
{includes}
"""


def find_sensor_files():
    """Find all *Sensor.h files that contain REGISTER_SENSOR."""
    sensors = []

    for path in sorted(SENSOR_DIR.glob("*Sensor.h")):
        # Skip infrastructure files
        if path.name in ("ISensor.h", "AllSensors.h"):
            continue

        content = path.read_text()
        if "REGISTER_SENSOR" in content:
            sensors.append(path.name)

    return sensors


def generate_header(sensor_files):
    """Generate AllSensors.h content."""
    includes = []
    for name in sensor_files:
        includes.append(f'#include "sensor/{name}"')

    includes_str = "\n".join(includes) if includes else "// No sensors discovered"
    return HEADER_TEMPLATE.format(includes=includes_str)


def main():
    """Generate AllSensors.h from discovered sensors."""
    sensor_files = find_sensor_files()

    content = generate_header(sensor_files)

    # Only write if changed (avoid unnecessary rebuilds)
    if OUTPUT_FILE.exists():
        existing = OUTPUT_FILE.read_text()
        if existing == content:
            print(f"AllSensors.h unchanged ({len(sensor_files)} sensors)")
            return

    OUTPUT_FILE.write_text(content)
    print(f"Generated AllSensors.h with {len(sensor_files)} sensors:")
    for s in sensor_files:
        print(f"  - {s}")


# PlatformIO pre-build hook entry point
try:
    Import("env")

    def before_build(source, target, env):
        """Called by PlatformIO before compilation."""
        main()

    # Register the pre-build action
    env.AddPreAction("buildprog", before_build)
except NameError:
    # Running standalone (not via PlatformIO)
    pass

if __name__ == "__main__":
    main()
