#!/usr/bin/env python3
"""
Pre-build script to auto-generate AllActuators.h

Scans for *Actuator.h files that contain REGISTER_ACTUATOR and generates
the include list. This enables 1-file actuator extensibility.

Usage:
  PlatformIO pre-build hook (see extra_scripts in platformio.ini)
  OR manual: python scripts/generate_all_actuators.py
"""

import inspect
import re
from pathlib import Path


def _resolve_script_path() -> Path:
    """Resolve this script path even when PlatformIO/SCons omits __file__."""
    file_value = globals().get("__file__")
    if file_value:
        return Path(file_value).resolve()

    source_file = inspect.getsourcefile(lambda: None) or inspect.getfile(lambda: None)
    if source_file and source_file != "<string>":
        return Path(source_file).resolve()

    candidate = (Path.cwd() / "scripts" / "generate_all_actuators.py").resolve()
    if candidate.exists():
        return candidate

    raise RuntimeError("Unable to resolve generate_all_actuators.py path")


SCRIPT_PATH = _resolve_script_path()
ACTUATOR_DIR = SCRIPT_PATH.parent.parent / "include" / "motor"
OUTPUT_FILE = ACTUATOR_DIR / "AllActuators.h"

HEADER_TEMPLATE = """\
// include/motor/AllActuators.h
// AUTO-GENERATED by scripts/generate_all_actuators.py
// DO NOT EDIT MANUALLY - changes will be overwritten
//
// To add a new actuator:
//   1. Create YourActuator.h implementing IActuator
//   2. Use REGISTER_ACTUATOR(YourActuator) macro
//   3. Rebuild - this file regenerates automatically

#pragma once

// Core infrastructure
#include "motor/ActuatorRegistry.h"

// Auto-discovered self-registering actuators
{includes}
"""


def find_actuator_files():
    """Find all *Actuator.h files that contain REGISTER_ACTUATOR."""
    actuators = []

    for path in sorted(ACTUATOR_DIR.glob("*Actuator.h")):
        # Skip infrastructure files
        if path.name in ("IActuator.h", "AllActuators.h"):
            continue

        content = path.read_text()
        if "REGISTER_ACTUATOR" in content:
            actuators.append(path.name)

    return actuators


def generate_header(actuator_files):
    """Generate AllActuators.h content."""
    includes = []
    for name in actuator_files:
        includes.append(f'#include "motor/{name}"')

    includes_str = "\n".join(includes) if includes else "// No actuators discovered"
    return HEADER_TEMPLATE.format(includes=includes_str)


def main():
    """Generate AllActuators.h from discovered actuators."""
    actuator_files = find_actuator_files()

    content = generate_header(actuator_files)

    # Only write if changed (avoid unnecessary rebuilds)
    if OUTPUT_FILE.exists():
        existing = OUTPUT_FILE.read_text()
        if existing == content:
            print(f"AllActuators.h unchanged ({len(actuator_files)} actuators)")
            return

    OUTPUT_FILE.write_text(content)
    print(f"Generated AllActuators.h with {len(actuator_files)} actuators:")
    for a in actuator_files:
        print(f"  - {a}")


# PlatformIO pre-build hook entry point
try:
    Import("env")

    def before_build(source, target, env):
        """Called by PlatformIO before compilation."""
        main()

    # Register the pre-build action
    env.AddPreAction("buildprog", before_build)
except NameError:
    # Running standalone (not via PlatformIO)
    pass

if __name__ == "__main__":
    main()
