from mara_host.command.client import MaraClient
from mara_host.core.event_bus import EventBus
from mara_host.core.host_module import CommandHostModule


class MotionHostModule(CommandHostModule):
    """High-level motion helpers (SET_VEL / STOP / ESTOP).

    Wraps the autogenerated cmd_* motion helpers on MaraClient.
    """

    module_name = "motion"

    def __init__(self, bus: EventBus, client: MaraClient) -> None:
        super().__init__(bus, client)

    async def set_velocity(self, vx: float, omega: float, frame: str = "robot") -> None:
        # Uses generated cmd_set_vel(vx, omega, frame)
        await self._client.cmd_set_vel(
            vx=float(vx),
            omega=float(omega),
            frame=frame,
        )

    async def stop(self) -> None:
        await self._client.cmd_stop()

    async def estop(self) -> None:
        await self._client.cmd_estop()

    async def clear_estop(self) -> None:
        await self._client.cmd_clear_estop()
