# AUTO-GENERATED - DO NOT EDIT
# Generated by: mara generate control
# Generated at: 2026-03-08T14:03:01.520334

"""Auto-generated palette entries from schema registry."""

# AUTO-GENERATED palette entries
# Add new blocks to tools/schema/control/ and regenerate

GENERATED_CONTROL_COMPONENTS = [
    # CONTROLLERS
    {"type": "pid", "label": "PID", "description": "PID controller with anti-windup", "color": "#3B82F6"},
    {"type": "lqr", "label": "LQR", "description": "Linear Quadratic Regulator", "color": "#8B5CF6"},
    {"type": "kalman_lqg", "label": "Kalman/LQG", "description": "Kalman filter with LQR control (LQG)", "color": "#22C55E"},
    {"type": "state_space", "label": "State-Space", "description": "Generic state-space controller", "color": "#EC4899"},
    {"type": "cascade_pid", "label": "Cascade PID", "description": "Cascaded inner/outer PID loops", "color": "#F59E0B"},
    {"type": "mpc", "label": "MPC", "description": "Model Predictive Controller (simplified)", "color": "#06B6D4"},
    {"type": "feedforward", "label": "Feedforward", "description": "Feedforward control (model inverse)", "color": "#A855F7"},
    # OBSERVERS
    {"type": "observer", "label": "Observer", "description": "Luenberger state observer", "color": "#22C55E"},
    {"type": "kalman", "label": "Kalman", "description": "Kalman filter (optimal observer)", "color": "#14B8A6"},
    {"type": "ekf", "label": "EKF", "description": "Extended Kalman Filter (nonlinear)", "color": "#F59E0B"},
    {"type": "complementary", "label": "Comp. Filter", "description": "Complementary filter (sensor fusion)", "color": "#EC4899"},
    {"type": "velocity_observer", "label": "Velocity Est.", "description": "Velocity estimator from position", "color": "#8B5CF6"},
    {"type": "disturbance_observer", "label": "DOB", "description": "Disturbance observer", "color": "#EF4444"},
    # FILTERS
    {"type": "integrator", "label": "Integrator", "description": "Integration (1/s)", "color": "#14B8A6"},
    {"type": "derivative", "label": "Derivative", "description": "Filtered derivative (s with filter)", "color": "#EC4899"},
    {"type": "filter", "label": "Filter", "description": "Low-pass filter", "color": "#A855F7"},
    {"type": "notch_filter", "label": "Notch", "description": "Notch filter (band-reject)", "color": "#06B6D4"},
    {"type": "moving_average", "label": "Moving Avg", "description": "Moving average filter", "color": "#22C55E"},
    {"type": "saturation", "label": "Saturation", "description": "Output limiter", "color": "#EF4444"},
    {"type": "deadzone", "label": "Deadzone", "description": "Deadzone nonlinearity", "color": "#F97316"},
    {"type": "rate_limiter", "label": "Rate Limit", "description": "Rate of change limiter", "color": "#EAB308"},
    {"type": "delay", "label": "Delay", "description": "Time delay", "color": "#F97316"},
    {"type": "transport_delay", "label": "Transport", "description": "Transport delay (discrete samples)", "color": "#D946EF"},
    # SIGNALS
    {"type": "signal_source", "label": "Signal", "description": "Signal source (reference input)", "color": "#3B82F6"},
    {"type": "signal_sink", "label": "Output", "description": "Signal sink (output)", "color": "#F59E0B"},
    {"type": "sum", "label": "Sum", "description": "Summing junction", "color": "#71717A"},
    {"type": "gain", "label": "Gain", "description": "Scalar gain", "color": "#8B5CF6"},
]
