# AUTO-GENERATED - DO NOT EDIT
# Generated by: mara generate control
# Generated at: 2026-03-08T14:03:01.519907
#
# To add a new control block:
#   1. Edit tools/schema/control/_controllers.py (or _observers.py, _filters.py)
#   2. Run: mara generate control
#   3. Your block will appear in the GUI palette automatically

"""Auto-generated control blocks from schema registry."""

from typing import Optional
from dataclasses import dataclass, field
from PySide6.QtCore import QPointF
from PySide6.QtGui import QColor

from ..core.block import BlockBase
from ..core.models import PortConfig, BlockConfig, PortKind, PortType



class PidBlock(BlockBase):
    """
    PID controller with anti-windup

    Auto-generated from schema/control registry.
    Category: controller
    """

    block_type = "pid"

    def __init__(self, block_id: str, label: str = "PID", **kwargs):
        ports = [
            PortConfig("ref", "REF", PortKind.INPUT, PortType.SIGNAL), PortConfig("meas", "MEAS", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="pid",
            label=label,
            ports=ports,
            color=QColor("#3B82F6"),
            width=80,
            height=60,
            properties={"kp": 1.0, "ki": 0.0, "kd": 0.0, "output_min": -1.0, "output_max": 1.0, "d_filter_coeff": 100.0, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class LqrBlock(BlockBase):
    """
    Linear Quadratic Regulator

    Auto-generated from schema/control registry.
    Category: controller
    """

    block_type = "lqr"

    def __init__(self, block_id: str, label: str = "LQR", **kwargs):
        ports = [
            PortConfig("ref", "REF", PortKind.INPUT, PortType.SIGNAL), PortConfig("state", "STATE", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="lqr",
            label=label,
            ports=ports,
            color=QColor("#8B5CF6"),
            width=80,
            height=60,
            properties={"num_states": 2, "num_inputs": 1, "K": [], "Q": [], "R": [], "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class KalmanLqgBlock(BlockBase):
    """
    Kalman filter with LQR control (LQG)

    Auto-generated from schema/control registry.
    Category: controller
    """

    block_type = "kalman_lqg"

    def __init__(self, block_id: str, label: str = "Kalman/LQG", **kwargs):
        ports = [
            PortConfig("ref", "REF", PortKind.INPUT, PortType.SIGNAL), PortConfig("u", "U", PortKind.INPUT, PortType.SIGNAL), PortConfig("y", "Y", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("x_hat", "X̂", PortKind.OUTPUT, PortType.SIGNAL), PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="kalman_lqg",
            label=label,
            ports=ports,
            color=QColor("#22C55E"),
            width=100,
            height=80,
            properties={"num_states": 2, "num_inputs": 1, "num_outputs": 1, "A": [], "B": [], "C": [], "K": [], "L": [], "Q_process": [], "R_meas": [], "controller_slot": 0, "observer_slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class StateSpaceBlock(BlockBase):
    """
    Generic state-space controller

    Auto-generated from schema/control registry.
    Category: controller
    """

    block_type = "state_space"

    def __init__(self, block_id: str, label: str = "State-Space", **kwargs):
        ports = [
            PortConfig("x", "X", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="state_space",
            label=label,
            ports=ports,
            color=QColor("#EC4899"),
            width=90,
            height=60,
            properties={"num_states": 2, "num_inputs": 1, "A": [], "B": [], "C": [], "D": [], "K": [], "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class CascadePidBlock(BlockBase):
    """
    Cascaded inner/outer PID loops

    Auto-generated from schema/control registry.
    Category: controller
    """

    block_type = "cascade_pid"

    def __init__(self, block_id: str, label: str = "Cascade PID", **kwargs):
        ports = [
            PortConfig("ref", "REF", PortKind.INPUT, PortType.SIGNAL), PortConfig("outer_meas", "OUTER", PortKind.INPUT, PortType.SIGNAL), PortConfig("inner_meas", "INNER", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="cascade_pid",
            label=label,
            ports=ports,
            color=QColor("#F59E0B"),
            width=120,
            height=70,
            properties={"outer_kp": 1.0, "outer_ki": 0.1, "outer_kd": 0.0, "inner_kp": 5.0, "inner_ki": 0.5, "inner_kd": 0.0, "inner_output_min": -1.0, "inner_output_max": 1.0, "outer_slot": 0, "inner_slot": 1},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class MpcBlock(BlockBase):
    """
    Model Predictive Controller (simplified)

    Auto-generated from schema/control registry.
    Category: controller
    """

    block_type = "mpc"

    def __init__(self, block_id: str, label: str = "MPC", **kwargs):
        ports = [
            PortConfig("ref", "REF", PortKind.INPUT, PortType.SIGNAL), PortConfig("state", "STATE", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="mpc",
            label=label,
            ports=ports,
            color=QColor("#06B6D4"),
            width=80,
            height=60,
            properties={"num_states": 2, "num_inputs": 1, "horizon": 10, "A": [], "B": [], "Q": [], "R": [], "u_min": -1.0, "u_max": 1.0, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class FeedforwardBlock(BlockBase):
    """
    Feedforward control (model inverse)

    Auto-generated from schema/control registry.
    Category: controller
    """

    block_type = "feedforward"

    def __init__(self, block_id: str, label: str = "Feedforward", **kwargs):
        ports = [
            PortConfig("ref", "REF", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="feedforward",
            label=label,
            ports=ports,
            color=QColor("#A855F7"),
            width=90,
            height=50,
            properties={"gain": 1.0, "velocity_gain": 0.0, "accel_gain": 0.0, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class ObserverBlock(BlockBase):
    """
    Luenberger state observer

    Auto-generated from schema/control registry.
    Category: observer
    """

    block_type = "observer"

    def __init__(self, block_id: str, label: str = "Observer", **kwargs):
        ports = [
            PortConfig("u", "U", PortKind.INPUT, PortType.SIGNAL), PortConfig("y", "Y", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("x_hat", "X̂", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="observer",
            label=label,
            ports=ports,
            color=QColor("#22C55E"),
            width=80,
            height=60,
            properties={"num_states": 2, "num_inputs": 1, "num_outputs": 1, "A": [], "B": [], "C": [], "L": [], "rate_hz": 200, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class KalmanBlock(BlockBase):
    """
    Kalman filter (optimal observer)

    Auto-generated from schema/control registry.
    Category: observer
    """

    block_type = "kalman"

    def __init__(self, block_id: str, label: str = "Kalman", **kwargs):
        ports = [
            PortConfig("u", "U", PortKind.INPUT, PortType.SIGNAL), PortConfig("y", "Y", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("x_hat", "X̂", PortKind.OUTPUT, PortType.SIGNAL), PortConfig("P", "P", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="kalman",
            label=label,
            ports=ports,
            color=QColor("#14B8A6"),
            width=80,
            height=70,
            properties={"num_states": 2, "num_inputs": 1, "num_outputs": 1, "A": [], "B": [], "C": [], "Q": [], "R": [], "rate_hz": 200, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class EkfBlock(BlockBase):
    """
    Extended Kalman Filter (nonlinear)

    Auto-generated from schema/control registry.
    Category: observer
    """

    block_type = "ekf"

    def __init__(self, block_id: str, label: str = "EKF", **kwargs):
        ports = [
            PortConfig("u", "U", PortKind.INPUT, PortType.SIGNAL), PortConfig("y", "Y", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("x_hat", "X̂", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="ekf",
            label=label,
            ports=ports,
            color=QColor("#F59E0B"),
            width=80,
            height=60,
            properties={"num_states": 3, "num_inputs": 1, "num_outputs": 1, "f_model": "linear", "h_model": "linear", "Q": [], "R": [], "rate_hz": 200, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class ComplementaryBlock(BlockBase):
    """
    Complementary filter (sensor fusion)

    Auto-generated from schema/control registry.
    Category: observer
    """

    block_type = "complementary"

    def __init__(self, block_id: str, label: str = "Comp. Filter", **kwargs):
        ports = [
            PortConfig("gyro", "GYRO", PortKind.INPUT, PortType.SIGNAL), PortConfig("accel", "ACCEL", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("angle", "θ", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="complementary",
            label=label,
            ports=ports,
            color=QColor("#EC4899"),
            width=100,
            height=60,
            properties={"alpha": 0.98, "dt": 0.01, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class VelocityObserverBlock(BlockBase):
    """
    Velocity estimator from position

    Auto-generated from schema/control registry.
    Category: observer
    """

    block_type = "velocity_observer"

    def __init__(self, block_id: str, label: str = "Velocity Est.", **kwargs):
        ports = [
            PortConfig("pos", "POS", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("vel", "VEL", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="velocity_observer",
            label=label,
            ports=ports,
            color=QColor("#8B5CF6"),
            width=90,
            height=50,
            properties={"filter_hz": 20.0, "rate_hz": 200, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class DisturbanceObserverBlock(BlockBase):
    """
    Disturbance observer

    Auto-generated from schema/control registry.
    Category: observer
    """

    block_type = "disturbance_observer"

    def __init__(self, block_id: str, label: str = "DOB", **kwargs):
        ports = [
            PortConfig("u", "U", PortKind.INPUT, PortType.SIGNAL), PortConfig("y", "Y", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("d_hat", "D̂", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="disturbance_observer",
            label=label,
            ports=ports,
            color=QColor("#EF4444"),
            width=80,
            height=60,
            properties={"num_states": 1, "bandwidth_hz": 10.0, "plant_gain": 1.0, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class SignalSourceBlock(BlockBase):
    """
    Signal source (reference input)

    Auto-generated from schema/control registry.
    Category: signal
    """

    block_type = "signal_source"

    def __init__(self, block_id: str, label: str = "Signal", **kwargs):
        ports = [
            
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="signal_source",
            label=label,
            ports=ports,
            color=QColor("#3B82F6"),
            width=60,
            height=40,
            properties={"signal_id": 0, "initial_value": 0.0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class SignalSinkBlock(BlockBase):
    """
    Signal sink (output)

    Auto-generated from schema/control registry.
    Category: signal
    """

    block_type = "signal_sink"

    def __init__(self, block_id: str, label: str = "Output", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="signal_sink",
            label=label,
            ports=ports,
            color=QColor("#F59E0B"),
            width=60,
            height=40,
            properties={"signal_id": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class SumBlock(BlockBase):
    """
    Summing junction

    Auto-generated from schema/control registry.
    Category: signal
    """

    block_type = "sum"

    def __init__(self, block_id: str, label: str = "Sum", **kwargs):
        ports = [
            PortConfig("in0", "+", PortKind.INPUT, PortType.SIGNAL), PortConfig("in1", "-", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="sum",
            label=label,
            ports=ports,
            color=QColor("#71717A"),
            width=40,
            height=40,
            properties={"signs": ['+', '-']},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class GainBlock(BlockBase):
    """
    Scalar gain

    Auto-generated from schema/control registry.
    Category: signal
    """

    block_type = "gain"

    def __init__(self, block_id: str, label: str = "Gain", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="gain",
            label=label,
            ports=ports,
            color=QColor("#8B5CF6"),
            width=50,
            height=40,
            properties={"gain": 1.0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class IntegratorBlock(BlockBase):
    """
    Integration (1/s)

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "integrator"

    def __init__(self, block_id: str, label: str = "Integrator", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="integrator",
            label=label,
            ports=ports,
            color=QColor("#14B8A6"),
            width=60,
            height=40,
            properties={"gain": 1.0, "limit_min": -1000.0, "limit_max": 1000.0, "initial_state": 0.0, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class DerivativeBlock(BlockBase):
    """
    Filtered derivative (s with filter)

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "derivative"

    def __init__(self, block_id: str, label: str = "Derivative", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="derivative",
            label=label,
            ports=ports,
            color=QColor("#EC4899"),
            width=60,
            height=40,
            properties={"gain": 1.0, "filter_coeff": 100.0, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class FilterBlock(BlockBase):
    """
    Low-pass filter

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "filter"

    def __init__(self, block_id: str, label: str = "Filter", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="filter",
            label=label,
            ports=ports,
            color=QColor("#A855F7"),
            width=60,
            height=40,
            properties={"cutoff_freq": 10.0, "order": 1, "filter_type": "lowpass", "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class NotchFilterBlock(BlockBase):
    """
    Notch filter (band-reject)

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "notch_filter"

    def __init__(self, block_id: str, label: str = "Notch", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="notch_filter",
            label=label,
            ports=ports,
            color=QColor("#06B6D4"),
            width=60,
            height=40,
            properties={"center_freq": 50.0, "bandwidth": 5.0, "depth_db": -40.0, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class MovingAverageBlock(BlockBase):
    """
    Moving average filter

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "moving_average"

    def __init__(self, block_id: str, label: str = "Moving Avg", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="moving_average",
            label=label,
            ports=ports,
            color=QColor("#22C55E"),
            width=70,
            height=40,
            properties={"window_size": 5, "slot": 0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class SaturationBlock(BlockBase):
    """
    Output limiter

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "saturation"

    def __init__(self, block_id: str, label: str = "Saturation", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="saturation",
            label=label,
            ports=ports,
            color=QColor("#EF4444"),
            width=60,
            height=40,
            properties={"lower": -1.0, "upper": 1.0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class DeadzoneBlock(BlockBase):
    """
    Deadzone nonlinearity

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "deadzone"

    def __init__(self, block_id: str, label: str = "Deadzone", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="deadzone",
            label=label,
            ports=ports,
            color=QColor("#F97316"),
            width=60,
            height=40,
            properties={"lower": -0.1, "upper": 0.1},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class RateLimiterBlock(BlockBase):
    """
    Rate of change limiter

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "rate_limiter"

    def __init__(self, block_id: str, label: str = "Rate Limit", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="rate_limiter",
            label=label,
            ports=ports,
            color=QColor("#EAB308"),
            width=70,
            height=40,
            properties={"rising_rate": 10.0, "falling_rate": 10.0},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class DelayBlock(BlockBase):
    """
    Time delay

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "delay"

    def __init__(self, block_id: str, label: str = "Delay", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="delay",
            label=label,
            ports=ports,
            color=QColor("#F97316"),
            width=60,
            height=40,
            properties={"delay_time": 0.1},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label


class TransportDelayBlock(BlockBase):
    """
    Transport delay (discrete samples)

    Auto-generated from schema/control registry.
    Category: filter
    """

    block_type = "transport_delay"

    def __init__(self, block_id: str, label: str = "Transport", **kwargs):
        ports = [
            PortConfig("in", "IN", PortKind.INPUT, PortType.SIGNAL),
            PortConfig("out", "OUT", PortKind.OUTPUT, PortType.SIGNAL),
        ]

        config = BlockConfig(
            block_id=block_id,
            block_type="transport_delay",
            label=label,
            ports=ports,
            color=QColor("#D946EF"),
            width=70,
            height=40,
            properties={"samples": 10},
        )
        config.properties.update(kwargs)
        super().__init__(config)

    def get_display_text(self) -> str:
        return self.config.label



__all__ = [
    "PidBlock",
    "LqrBlock",
    "KalmanLqgBlock",
    "StateSpaceBlock",
    "CascadePidBlock",
    "MpcBlock",
    "FeedforwardBlock",
    "ObserverBlock",
    "KalmanBlock",
    "EkfBlock",
    "ComplementaryBlock",
    "VelocityObserverBlock",
    "DisturbanceObserverBlock",
    "SignalSourceBlock",
    "SignalSinkBlock",
    "SumBlock",
    "GainBlock",
    "IntegratorBlock",
    "DerivativeBlock",
    "FilterBlock",
    "NotchFilterBlock",
    "MovingAverageBlock",
    "SaturationBlock",
    "DeadzoneBlock",
    "RateLimiterBlock",
    "DelayBlock",
    "TransportDelayBlock",
]
