# mara_host/services/codegen/generator_service.py
"""
Code generation service.

Provides a clean interface for running code generators that produce
both Python and C++ code from the platform schema.
"""

import sys
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional, Callable
import importlib


class GeneratorType(Enum):
    """Available code generators."""
    COMMANDS = "commands"
    PINS = "pins"
    GPIO = "gpio"
    BINARY = "binary"
    TELEMETRY = "telemetry"
    CAN = "can"
    VERSION = "version"


@dataclass
class GeneratorResult:
    """Result of a generator run."""
    generator: GeneratorType
    success: bool
    message: str = ""
    files_generated: list[str] = field(default_factory=list)
    error: Optional[str] = None


@dataclass
class GenerationSummary:
    """Summary of all generators run."""
    results: list[GeneratorResult]
    total_files: int = 0

    @property
    def all_success(self) -> bool:
        return all(r.success for r in self.results)

    @property
    def failed_count(self) -> int:
        return sum(1 for r in self.results if not r.success)


class CodeGeneratorService:
    """
    Service for running code generators.

    Example:
        service = CodeGeneratorService()

        # Run all generators
        summary = service.generate_all()

        # Run specific generator
        result = service.generate(GeneratorType.COMMANDS)

        # Check what would be generated
        files = service.list_generated_files()
    """

    # Map generator type to module name
    _GENERATOR_MODULES = {
        GeneratorType.COMMANDS: "gen_commands",
        GeneratorType.PINS: "generate_pins",
        GeneratorType.GPIO: "gpio_mapping_gen",
        GeneratorType.BINARY: "gen_binary_commands",
        GeneratorType.TELEMETRY: "gen_telemetry",
        GeneratorType.CAN: "gen_can",
        GeneratorType.VERSION: "gen_version",
    }

    # Files generated by each generator
    _GENERATED_FILES = {
        GeneratorType.COMMANDS: [
            "mara_host/config/client_commands.py",
            "mara_host/config/command_defs.py",
            "mara_host/config/commands.json",
            "ESP32 MCU Host/include/command/CommandDefs.h",
        ],
        GeneratorType.PINS: [
            "mara_host/config/pin_config.py",
            "mara_host/config/pins.json",
            "ESP32 MCU Host/include/config/PinConfig.h",
        ],
        GeneratorType.GPIO: [
            "mara_host/config/gpio_channels.py",
            "mara_host/config/gpio_channels.json",
            "ESP32 MCU Host/include/config/GpioChannelDefs.h",
        ],
        GeneratorType.BINARY: [
            "mara_host/command/binary_commands.py",
            "mara_host/command/json_to_binary.py",
            "ESP32 MCU Host/include/command/BinaryCommands.h",
        ],
        GeneratorType.TELEMETRY: [
            "mara_host/telemetry/telemetry_sections.py",
            "ESP32 MCU Host/include/telemetry/TelemetrySections.h",
        ],
        GeneratorType.CAN: [
            "mara_host/transport/can_defs_generated.py",
            "ESP32 MCU Host/include/transport/CanDefs.h",
        ],
        GeneratorType.VERSION: [
            "mara_host/config/version.py",
            "ESP32 MCU Host/include/config/Version.h",
        ],
    }

    def __init__(self):
        """Initialize code generator service."""
        self._tools_dir = Path(__file__).parent.parent.parent / "tools"
        self._progress_callback: Optional[Callable[[GeneratorType, str], None]] = None

        # Ensure tools dir is in path
        if str(self._tools_dir) not in sys.path:
            sys.path.insert(0, str(self._tools_dir))

    def generate_all(self) -> GenerationSummary:
        """
        Run all code generators.

        Returns:
            GenerationSummary with results for each generator
        """
        results = []

        # Run in dependency order
        order = [
            GeneratorType.VERSION,
            GeneratorType.COMMANDS,
            GeneratorType.PINS,
            GeneratorType.GPIO,
            GeneratorType.BINARY,
            GeneratorType.TELEMETRY,
            GeneratorType.CAN,
        ]

        for gen_type in order:
            result = self.generate(gen_type)
            results.append(result)

            if not result.success:
                # Continue anyway to report all errors
                pass

        total_files = sum(len(r.files_generated) for r in results if r.success)

        return GenerationSummary(results=results, total_files=total_files)

    def generate(self, generator_type: GeneratorType) -> GeneratorResult:
        """
        Run a specific generator.

        Args:
            generator_type: Which generator to run

        Returns:
            GeneratorResult with status
        """
        module_name = self._GENERATOR_MODULES.get(generator_type)
        if not module_name:
            return GeneratorResult(
                generator=generator_type,
                success=False,
                error=f"Unknown generator type: {generator_type}"
            )

        self._notify_progress(generator_type, f"Running {module_name}...")

        try:
            # Import and run the generator
            module = importlib.import_module(module_name)

            # Reload to ensure fresh state
            importlib.reload(module)

            # Run main function
            if hasattr(module, 'main'):
                module.main()

            files = self._GENERATED_FILES.get(generator_type, [])

            return GeneratorResult(
                generator=generator_type,
                success=True,
                message=f"Generated {len(files)} files",
                files_generated=files,
            )

        except Exception as e:
            return GeneratorResult(
                generator=generator_type,
                success=False,
                error=str(e),
            )

    def list_generated_files(
        self,
        generator_type: Optional[GeneratorType] = None
    ) -> dict[GeneratorType, list[str]]:
        """
        List files that would be generated.

        Args:
            generator_type: Specific generator, or None for all

        Returns:
            Dict mapping generator type to list of file paths
        """
        if generator_type:
            return {generator_type: self._GENERATED_FILES.get(generator_type, [])}

        return {gt: list(files) for gt, files in self._GENERATED_FILES.items()}

    def get_schema_path(self) -> Path:
        """Get path to the platform schema (source of truth)."""
        return self._tools_dir / "platform_schema.py"

    def set_progress_callback(
        self,
        callback: Callable[[GeneratorType, str], None]
    ) -> None:
        """Set callback for progress updates."""
        self._progress_callback = callback

    def _notify_progress(self, gen_type: GeneratorType, message: str) -> None:
        """Notify progress callback if set."""
        if self._progress_callback:
            self._progress_callback(gen_type, message)

    @staticmethod
    def get_available_generators() -> list[GeneratorType]:
        """Get list of available generators."""
        return list(GeneratorType)
