# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: tools/gen_tooling_backends.py
# Generated at: 2026-04-02T11:59:13.921713
"""
Auto-generated backend loaders.

This module is imported by registry.py to auto-load all discovered backends.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .registry import BackendRegistry


# Discovered backends:
#   - cmake
#   - platformio


def load_all_backends(registry: BackendRegistry) -> list[str]:
    """Load all discovered backends into the registry.

    Returns:
        List of successfully loaded backend names.
    """
    loaded = []

    # cmake
    try:
        from .implementations.cmake import register_backends as register_cmake
        register_cmake(registry)
        loaded.append("cmake")
    except ImportError:
        pass

    # platformio
    try:
        from .implementations.platformio import register_backends as register_platformio
        register_platformio(registry)
        loaded.append("platformio")
    except ImportError:
        pass

    return loaded
