# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: tools/gen_mcp_servers.py
# Generated at: 2026-03-26T18:13:25.224875
"""
Generated HTTP handlers and routes.
"""

from __future__ import annotations

from datetime import datetime
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Route


def create_generated_routes(runtime) -> list[Route]:
    """Create routes for all generated tools."""

    async def handle_wifi_status(request: Request) -> JSONResponse:
        """POST /wifi/status"""
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.wifi_service.status()
        runtime.record_command("wifi_status", {}, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_wifi_join(request: Request) -> JSONResponse:
        """POST /wifi/join"""
        await runtime.ensure_connected()
        body = await request.json()
        ssid = body.get("ssid")
        if ssid is None:
            return JSONResponse({"ok": False, "error": "ssid required"}, status_code=400)
        password = body.get("password")
        if password is None:
            return JSONResponse({"ok": False, "error": "password required"}, status_code=400)
        wait_for_connect = body.get("wait_for_connect", True)
        timeout_ms = body.get("timeout_ms", 10000)
        sent_at = datetime.now()
        result = await runtime.wifi_service.join(ssid=ssid, password=password, wait_for_connect=wait_for_connect, timeout_ms=timeout_ms)
        runtime.record_command("wifi_join", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_wifi_disconnect(request: Request) -> JSONResponse:
        """POST /wifi/disconnect"""
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.wifi_service.disconnect()
        runtime.record_command("wifi_disconnect", {}, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_arm(request: Request) -> JSONResponse:
        """POST /state/arm"""
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.state_service.arm()
        runtime.sync_state_result(result)
        runtime.record_command("arm", {}, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_disarm(request: Request) -> JSONResponse:
        """POST /state/disarm"""
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.state_service.disarm()
        runtime.sync_state_result(result)
        runtime.record_command("disarm", {}, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_stop(request: Request) -> JSONResponse:
        """POST /state/stop"""
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.state_service.stop()
        runtime.sync_state_result(result)
        runtime.record_command("stop", {}, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_servo_attach(request: Request) -> JSONResponse:
        """POST /servo/attach"""
        await runtime.ensure_armed()
        body = await request.json()
        servo_id = body.get("servo_id")
        if servo_id is None:
            return JSONResponse({"ok": False, "error": "servo_id required"}, status_code=400)
        pin = body.get("pin")
        if pin is None:
            return JSONResponse({"ok": False, "error": "pin required"}, status_code=400)
        min_us = body.get("min_us", 500)
        max_us = body.get("max_us", 2500)
        sent_at = datetime.now()
        result = await runtime.servo_service.attach(servo_id=servo_id, channel=pin, min_us=min_us, max_us=max_us)
        runtime.record_command("servo_attach", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_servo_set(request: Request) -> JSONResponse:
        """POST /servo/set"""
        await runtime.ensure_armed()
        body = await request.json()
        servo_id = body.get("servo_id")
        if servo_id is None:
            return JSONResponse({"ok": False, "error": "servo_id required"}, status_code=400)
        angle = body.get("angle")
        if angle is None:
            return JSONResponse({"ok": False, "error": "angle required"}, status_code=400)
        duration_ms = body.get("duration_ms", 300)
        sent_at = datetime.now()
        result = await runtime.servo_service.set_angle(servo_id=servo_id, angle=angle, duration_ms=duration_ms)
        runtime.record_command("servo_set", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_servo_center(request: Request) -> JSONResponse:
        """POST /servo/center"""
        await runtime.ensure_armed()
        body = await request.json()
        servo_id = body.get("servo_id")
        if servo_id is None:
            return JSONResponse({"ok": False, "error": "servo_id required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.servo_service.center(servo_id=servo_id)
        runtime.record_command("servo_center", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_servo_detach(request: Request) -> JSONResponse:
        """POST /servo/detach"""
        await runtime.ensure_armed()
        body = await request.json()
        servo_id = body.get("servo_id")
        if servo_id is None:
            return JSONResponse({"ok": False, "error": "servo_id required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.servo_service.detach(servo_id=servo_id)
        runtime.record_command("servo_detach", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_motor_set(request: Request) -> JSONResponse:
        """POST /motor/set"""
        await runtime.ensure_armed()
        body = await request.json()
        motor_id = body.get("motor_id")
        if motor_id is None:
            return JSONResponse({"ok": False, "error": "motor_id required"}, status_code=400)
        speed = body.get("speed")
        if speed is None:
            return JSONResponse({"ok": False, "error": "speed required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.motor_service.set_speed(motor_id=motor_id, speed=speed)
        runtime.record_command("motor_set", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_motor_stop(request: Request) -> JSONResponse:
        """POST /motor/stop"""
        await runtime.ensure_armed()
        body = await request.json()
        motor_id = body.get("motor_id")
        if motor_id is None:
            return JSONResponse({"ok": False, "error": "motor_id required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.motor_service.stop(motor_id=motor_id)
        runtime.record_command("motor_stop", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_gpio_write(request: Request) -> JSONResponse:
        """POST /gpio/write"""
        await runtime.ensure_armed()
        body = await request.json()
        channel = body.get("channel")
        if channel is None:
            return JSONResponse({"ok": False, "error": "channel required"}, status_code=400)
        value = body.get("value")
        if value is None:
            return JSONResponse({"ok": False, "error": "value required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.gpio_service.write(channel=channel, value=value)
        runtime.record_command("gpio_write", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_gpio_toggle(request: Request) -> JSONResponse:
        """POST /gpio/toggle"""
        await runtime.ensure_armed()
        body = await request.json()
        channel = body.get("channel")
        if channel is None:
            return JSONResponse({"ok": False, "error": "channel required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.gpio_service.toggle(channel=channel)
        runtime.record_command("gpio_toggle", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_gpio_read(request: Request) -> JSONResponse:
        """POST /gpio/read"""
        await runtime.ensure_connected()
        body = await request.json()
        channel = body.get("channel")
        if channel is None:
            return JSONResponse({"ok": False, "error": "channel required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.gpio_service.read(channel=channel)
        runtime.record_command("gpio_read", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_stepper_move(request: Request) -> JSONResponse:
        """POST /stepper/move"""
        await runtime.ensure_armed()
        body = await request.json()
        stepper_id = body.get("stepper_id")
        if stepper_id is None:
            return JSONResponse({"ok": False, "error": "stepper_id required"}, status_code=400)
        steps = body.get("steps")
        if steps is None:
            return JSONResponse({"ok": False, "error": "steps required"}, status_code=400)
        speed = body.get("speed", None)
        sent_at = datetime.now()
        result = await runtime.stepper_service.move_relative(stepper_id=stepper_id, steps=steps, speed=speed)
        runtime.record_command("stepper_move", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_stepper_stop(request: Request) -> JSONResponse:
        """POST /stepper/stop"""
        await runtime.ensure_armed()
        body = await request.json()
        stepper_id = body.get("stepper_id")
        if stepper_id is None:
            return JSONResponse({"ok": False, "error": "stepper_id required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.stepper_service.stop(stepper_id=stepper_id)
        runtime.record_command("stepper_stop", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_pwm_set(request: Request) -> JSONResponse:
        """POST /pwm/set"""
        await runtime.ensure_armed()
        body = await request.json()
        channel = body.get("channel")
        if channel is None:
            return JSONResponse({"ok": False, "error": "channel required"}, status_code=400)
        duty = body.get("duty")
        if duty is None:
            return JSONResponse({"ok": False, "error": "duty required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.pwm_service.set_duty(channel=channel, duty=duty)
        runtime.record_command("pwm_set", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_encoder_read(request: Request) -> JSONResponse:
        """POST /encoder/read"""
        await runtime.ensure_connected()
        body = await request.json()
        encoder_id = body.get("encoder_id")
        if encoder_id is None:
            return JSONResponse({"ok": False, "error": "encoder_id required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.encoder_service.read(encoder_id=encoder_id)
        runtime.record_command("encoder_read", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_encoder_reset(request: Request) -> JSONResponse:
        """POST /encoder/reset"""
        await runtime.ensure_armed()
        body = await request.json()
        encoder_id = body.get("encoder_id")
        if encoder_id is None:
            return JSONResponse({"ok": False, "error": "encoder_id required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.encoder_service.reset(encoder_id=encoder_id)
        runtime.record_command("encoder_reset", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_imu_read(request: Request) -> JSONResponse:
        """POST /imu/read"""
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.imu_service.read()
        runtime.record_command("imu_read", {}, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_ultrasonic_attach(request: Request) -> JSONResponse:
        """POST /ultrasonic/attach"""
        await runtime.ensure_connected()
        body = await request.json()
        sensor_id = body.get("sensor_id")
        if sensor_id is None:
            return JSONResponse({"ok": False, "error": "sensor_id required"}, status_code=400)
        trig_pin = body.get("trig_pin")
        if trig_pin is None:
            return JSONResponse({"ok": False, "error": "trig_pin required"}, status_code=400)
        echo_pin = body.get("echo_pin")
        if echo_pin is None:
            return JSONResponse({"ok": False, "error": "echo_pin required"}, status_code=400)
        max_distance_cm = body.get("max_distance_cm", 400.0)
        sent_at = datetime.now()
        result = await runtime.ultrasonic_service.attach(sensor_id=sensor_id, trig_pin=trig_pin, echo_pin=echo_pin, max_distance_cm=max_distance_cm)
        runtime.record_command("ultrasonic_attach", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_ultrasonic_read(request: Request) -> JSONResponse:
        """POST /ultrasonic/read"""
        await runtime.ensure_connected()
        body = await request.json()
        sensor_id = body.get("sensor_id")
        if sensor_id is None:
            return JSONResponse({"ok": False, "error": "sensor_id required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.ultrasonic_service.read(sensor_id=sensor_id)
        runtime.record_command("ultrasonic_read", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_ultrasonic_detach(request: Request) -> JSONResponse:
        """POST /ultrasonic/detach"""
        await runtime.ensure_connected()
        body = await request.json()
        sensor_id = body.get("sensor_id")
        if sensor_id is None:
            return JSONResponse({"ok": False, "error": "sensor_id required"}, status_code=400)
        sent_at = datetime.now()
        result = await runtime.ultrasonic_service.detach(sensor_id=sensor_id)
        runtime.record_command("ultrasonic_detach", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_robot_move(request: Request) -> JSONResponse:
        """POST /robot/move"""
        await runtime.ensure_armed()
        body = await request.json()
        moves = body.get("moves")
        if moves is None:
            return JSONResponse({"ok": False, "error": "moves required"}, status_code=400)
        duration_ms = body.get("duration_ms", 300)
        sent_at = datetime.now()
        result = await runtime.robot_service.move_joints(moves=moves, duration_ms=duration_ms)
        runtime.record_command("robot_move", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    async def handle_robot_home(request: Request) -> JSONResponse:
        """POST /robot/home"""
        await runtime.ensure_armed()
        body = await request.json()
        joints = body.get("joints", None)
        duration_ms = body.get("duration_ms", 500)
        sent_at = datetime.now()
        result = await runtime.robot_service.home(joints=joints, duration_ms=duration_ms)
        runtime.record_command("robot_home", body, result.ok, result.error, sent_at=sent_at)
        return JSONResponse({"ok": result.ok, "error": result.error, "state": getattr(result, 'state', None), "data": getattr(result, 'data', None)})

    # Build routes list
    routes = [
        Route("/wifi/status", handle_wifi_status, methods=["POST"]),
        Route("/wifi/join", handle_wifi_join, methods=["POST"]),
        Route("/wifi/disconnect", handle_wifi_disconnect, methods=["POST"]),
        Route("/state/arm", handle_arm, methods=["POST"]),
        Route("/state/disarm", handle_disarm, methods=["POST"]),
        Route("/state/stop", handle_stop, methods=["POST"]),
        Route("/servo/attach", handle_servo_attach, methods=["POST"]),
        Route("/servo/set", handle_servo_set, methods=["POST"]),
        Route("/servo/center", handle_servo_center, methods=["POST"]),
        Route("/servo/detach", handle_servo_detach, methods=["POST"]),
        Route("/motor/set", handle_motor_set, methods=["POST"]),
        Route("/motor/stop", handle_motor_stop, methods=["POST"]),
        Route("/gpio/write", handle_gpio_write, methods=["POST"]),
        Route("/gpio/toggle", handle_gpio_toggle, methods=["POST"]),
        Route("/gpio/read", handle_gpio_read, methods=["POST"]),
        Route("/stepper/move", handle_stepper_move, methods=["POST"]),
        Route("/stepper/stop", handle_stepper_stop, methods=["POST"]),
        Route("/pwm/set", handle_pwm_set, methods=["POST"]),
        Route("/encoder/read", handle_encoder_read, methods=["POST"]),
        Route("/encoder/reset", handle_encoder_reset, methods=["POST"]),
        Route("/imu/read", handle_imu_read, methods=["POST"]),
        Route("/ultrasonic/attach", handle_ultrasonic_attach, methods=["POST"]),
        Route("/ultrasonic/read", handle_ultrasonic_read, methods=["POST"]),
        Route("/ultrasonic/detach", handle_ultrasonic_detach, methods=["POST"]),
        Route("/robot/move", handle_robot_move, methods=["POST"]),
        Route("/robot/home", handle_robot_home, methods=["POST"]),
    ]
    return routes


def get_openai_function_schema() -> list[dict]:
    """Get OpenAI-compatible function definitions for LLMs."""
    return [
        {
            "name": "mara_wifi_status",
            "description": "Get current Wi‑Fi status including STA/AP mode and IPs.",
            "parameters": {'type': 'object', 'properties': {}},
        },
        {
            "name": "mara_wifi_join",
            "description": "Join a Wi‑Fi network at runtime while keeping AP recovery available.",
            "parameters": {'type': 'object', 'properties': {'ssid': {'type': 'string', 'description': 'Wi‑Fi SSID'}, 'password': {'type': 'string', 'description': 'Wi‑Fi password'}, 'wait_for_connect': {'type': 'boolean', 'description': 'Wait for connection result before replying', 'default': True}, 'timeout_ms': {'type': 'integer', 'description': 'Join timeout in milliseconds', 'default': 10000}}, 'required': ['ssid', 'password']},
        },
        {
            "name": "mara_wifi_disconnect",
            "description": "Disconnect station Wi‑Fi while leaving AP recovery intact.",
            "parameters": {'type': 'object', 'properties': {}},
        },
        {
            "name": "mara_arm",
            "description": "Arm the robot for operation. Required before moving actuators.",
            "parameters": {'type': 'object', 'properties': {}},
        },
        {
            "name": "mara_disarm",
            "description": "Disarm the robot. Stops all motion.",
            "parameters": {'type': 'object', 'properties': {}},
        },
        {
            "name": "mara_stop",
            "description": "Emergency stop - immediately halt all motion.",
            "parameters": {'type': 'object', 'properties': {}},
        },
        {
            "name": "mara_servo_attach",
            "description": "Attach a servo to a GPIO pin.",
            "parameters": {'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}, 'pin': {'type': 'integer', 'description': 'GPIO pin number'}, 'min_us': {'type': 'integer', 'description': 'Min pulse width in microseconds', 'default': 500}, 'max_us': {'type': 'integer', 'description': 'Max pulse width in microseconds', 'default': 2500}}, 'required': ['servo_id', 'pin']},
        },
        {
            "name": "mara_servo_set",
            "description": "Move a servo to the specified angle.",
            "parameters": {'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}, 'angle': {'type': 'number', 'description': 'Angle in degrees (0-180)'}, 'duration_ms': {'type': 'integer', 'description': 'Movement duration in ms (0=instant)', 'default': 300}}, 'required': ['servo_id', 'angle']},
        },
        {
            "name": "mara_servo_center",
            "description": "Move servo to center position (90 degrees).",
            "parameters": {'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}}, 'required': ['servo_id']},
        },
        {
            "name": "mara_servo_detach",
            "description": "Detach a servo from its pin.",
            "parameters": {'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}}, 'required': ['servo_id']},
        },
        {
            "name": "mara_motor_set",
            "description": "Set DC motor speed.",
            "parameters": {'type': 'object', 'properties': {'motor_id': {'type': 'integer', 'description': 'Motor ID (0-3)'}, 'speed': {'type': 'number', 'description': 'Speed (-1.0 to 1.0)'}}, 'required': ['motor_id', 'speed']},
        },
        {
            "name": "mara_motor_stop",
            "description": "Stop a DC motor.",
            "parameters": {'type': 'object', 'properties': {'motor_id': {'type': 'integer', 'description': 'Motor ID (0-3)'}}, 'required': ['motor_id']},
        },
        {
            "name": "mara_gpio_write",
            "description": "Set GPIO pin high or low.",
            "parameters": {'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}, 'value': {'type': 'integer', 'description': '0=low, 1=high'}}, 'required': ['channel', 'value']},
        },
        {
            "name": "mara_gpio_toggle",
            "description": "Toggle GPIO pin state.",
            "parameters": {'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}}, 'required': ['channel']},
        },
        {
            "name": "mara_gpio_read",
            "description": "Read GPIO pin state.",
            "parameters": {'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}}, 'required': ['channel']},
        },
        {
            "name": "mara_stepper_move",
            "description": "Move stepper motor by relative steps.",
            "parameters": {'type': 'object', 'properties': {'stepper_id': {'type': 'integer', 'description': 'Stepper ID'}, 'steps': {'type': 'integer', 'description': 'Steps to move (negative=reverse)'}, 'speed': {'type': 'number', 'description': 'Speed in steps/second'}}, 'required': ['stepper_id', 'steps']},
        },
        {
            "name": "mara_stepper_stop",
            "description": "Stop a stepper motor.",
            "parameters": {'type': 'object', 'properties': {'stepper_id': {'type': 'integer', 'description': 'Stepper ID'}}, 'required': ['stepper_id']},
        },
        {
            "name": "mara_pwm_set",
            "description": "Set PWM duty cycle on a channel.",
            "parameters": {'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'PWM channel'}, 'duty': {'type': 'number', 'description': 'Duty cycle (0.0-1.0)'}}, 'required': ['channel', 'duty']},
        },
        {
            "name": "mara_encoder_read",
            "description": "Read encoder value.",
            "parameters": {'type': 'object', 'properties': {'encoder_id': {'type': 'integer', 'description': 'Encoder ID'}}, 'required': ['encoder_id']},
        },
        {
            "name": "mara_encoder_reset",
            "description": "Reset encoder count to zero.",
            "parameters": {'type': 'object', 'properties': {'encoder_id': {'type': 'integer', 'description': 'Encoder ID'}}, 'required': ['encoder_id']},
        },
        {
            "name": "mara_imu_read",
            "description": "Read IMU sensor data (accelerometer and gyroscope).",
            "parameters": {'type': 'object', 'properties': {}},
        },
        {
            "name": "mara_ultrasonic_attach",
            "description": "Attach an ultrasonic distance sensor to GPIO pins.",
            "parameters": {'type': 'object', 'properties': {'sensor_id': {'type': 'integer', 'description': 'Sensor ID (0-3)'}, 'trig_pin': {'type': 'integer', 'description': 'Trigger GPIO pin'}, 'echo_pin': {'type': 'integer', 'description': 'Echo GPIO pin'}, 'max_distance_cm': {'type': 'number', 'description': 'Maximum measurable distance in cm', 'default': 400.0}}, 'required': ['sensor_id', 'trig_pin', 'echo_pin']},
        },
        {
            "name": "mara_ultrasonic_read",
            "description": "Read distance from ultrasonic sensor in centimeters.",
            "parameters": {'type': 'object', 'properties': {'sensor_id': {'type': 'integer', 'description': 'Sensor ID (0-3)'}}, 'required': ['sensor_id']},
        },
        {
            "name": "mara_ultrasonic_detach",
            "description": "Detach an ultrasonic sensor.",
            "parameters": {'type': 'object', 'properties': {'sensor_id': {'type': 'integer', 'description': 'Sensor ID (0-3)'}}, 'required': ['sensor_id']},
        },
        {
            "name": "mara_robot_move",
            "description": "Move one or more joints by name. Joints move simultaneously. Provide moves as JSON array.",
            "parameters": {'type': 'object', 'properties': {'moves': {'type': 'string', 'description': 'JSON array of moves, e.g. [{joint: shoulder, angle: 45}]'}, 'duration_ms': {'type': 'integer', 'description': 'Movement duration in milliseconds', 'default': 300}}, 'required': ['moves']},
        },
        {
            "name": "mara_robot_home",
            "description": "Move all joints (or specified joints) to their home positions.",
            "parameters": {'type': 'object', 'properties': {'joints': {'type': 'string', 'description': 'JSON array of joint names to home, or omit for all joints'}, 'duration_ms': {'type': 'integer', 'description': 'Movement duration in milliseconds', 'default': 500}}},
        },
    ]
