# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: tools/gen_mcp_servers.py
# Generated at: 2026-03-26T18:13:25.224439
"""
Generated MCP tool definitions and dispatch.
"""

from __future__ import annotations

from typing import Any
from datetime import datetime
from mcp.types import Tool, TextContent


def get_tool_definitions() -> list[Tool]:
    """Return list of MCP Tool definitions."""
    return [
        Tool(
            name="mara_connect",
            description="Connect to the robot. Auto-connects if needed for other commands.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_disconnect",
            description="Disconnect from the robot.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_get_state",
            description="Get current robot state including connection, arm status, telemetry, and recent commands.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_get_freshness",
            description="Get data freshness report - shows which sensor data is fresh, aging, or stale.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_get_events",
            description="Get recent events (state changes, commands, errors).",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_get_command_stats",
            description="Get command statistics (success rate, latency, pending count).",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_wifi_status",
            description="Get current Wi‑Fi status including STA/AP mode and IPs.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_wifi_join",
            description="Join a Wi‑Fi network at runtime while keeping AP recovery available.",
            inputSchema={'type': 'object', 'properties': {'ssid': {'type': 'string', 'description': 'Wi‑Fi SSID'}, 'password': {'type': 'string', 'description': 'Wi‑Fi password'}, 'wait_for_connect': {'type': 'boolean', 'description': 'Wait for connection result before replying', 'default': True}, 'timeout_ms': {'type': 'integer', 'description': 'Join timeout in milliseconds', 'default': 10000}}, 'required': ['ssid', 'password']},
        ),
        Tool(
            name="mara_wifi_disconnect",
            description="Disconnect station Wi‑Fi while leaving AP recovery intact.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_arm",
            description="Arm the robot for operation. Required before moving actuators.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_disarm",
            description="Disarm the robot. Stops all motion.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_stop",
            description="Emergency stop - immediately halt all motion.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_servo_attach",
            description="Attach a servo to a GPIO pin.",
            inputSchema={'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}, 'pin': {'type': 'integer', 'description': 'GPIO pin number'}, 'min_us': {'type': 'integer', 'description': 'Min pulse width in microseconds', 'default': 500}, 'max_us': {'type': 'integer', 'description': 'Max pulse width in microseconds', 'default': 2500}}, 'required': ['servo_id', 'pin']},
        ),
        Tool(
            name="mara_servo_set",
            description="Move a servo to the specified angle.",
            inputSchema={'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}, 'angle': {'type': 'number', 'description': 'Angle in degrees (0-180)'}, 'duration_ms': {'type': 'integer', 'description': 'Movement duration in ms (0=instant)', 'default': 300}}, 'required': ['servo_id', 'angle']},
        ),
        Tool(
            name="mara_servo_center",
            description="Move servo to center position (90 degrees).",
            inputSchema={'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}}, 'required': ['servo_id']},
        ),
        Tool(
            name="mara_servo_detach",
            description="Detach a servo from its pin.",
            inputSchema={'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}}, 'required': ['servo_id']},
        ),
        Tool(
            name="mara_motor_set",
            description="Set DC motor speed.",
            inputSchema={'type': 'object', 'properties': {'motor_id': {'type': 'integer', 'description': 'Motor ID (0-3)'}, 'speed': {'type': 'number', 'description': 'Speed (-1.0 to 1.0)'}}, 'required': ['motor_id', 'speed']},
        ),
        Tool(
            name="mara_motor_stop",
            description="Stop a DC motor.",
            inputSchema={'type': 'object', 'properties': {'motor_id': {'type': 'integer', 'description': 'Motor ID (0-3)'}}, 'required': ['motor_id']},
        ),
        Tool(
            name="mara_gpio_write",
            description="Set GPIO pin high or low.",
            inputSchema={'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}, 'value': {'type': 'integer', 'description': '0=low, 1=high'}}, 'required': ['channel', 'value']},
        ),
        Tool(
            name="mara_gpio_toggle",
            description="Toggle GPIO pin state.",
            inputSchema={'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}}, 'required': ['channel']},
        ),
        Tool(
            name="mara_gpio_read",
            description="Read GPIO pin state.",
            inputSchema={'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}}, 'required': ['channel']},
        ),
        Tool(
            name="mara_stepper_move",
            description="Move stepper motor by relative steps.",
            inputSchema={'type': 'object', 'properties': {'stepper_id': {'type': 'integer', 'description': 'Stepper ID'}, 'steps': {'type': 'integer', 'description': 'Steps to move (negative=reverse)'}, 'speed': {'type': 'number', 'description': 'Speed in steps/second'}}, 'required': ['stepper_id', 'steps']},
        ),
        Tool(
            name="mara_stepper_stop",
            description="Stop a stepper motor.",
            inputSchema={'type': 'object', 'properties': {'stepper_id': {'type': 'integer', 'description': 'Stepper ID'}}, 'required': ['stepper_id']},
        ),
        Tool(
            name="mara_pwm_set",
            description="Set PWM duty cycle on a channel.",
            inputSchema={'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'PWM channel'}, 'duty': {'type': 'number', 'description': 'Duty cycle (0.0-1.0)'}}, 'required': ['channel', 'duty']},
        ),
        Tool(
            name="mara_encoder_read",
            description="Read encoder value.",
            inputSchema={'type': 'object', 'properties': {'encoder_id': {'type': 'integer', 'description': 'Encoder ID'}}, 'required': ['encoder_id']},
        ),
        Tool(
            name="mara_encoder_reset",
            description="Reset encoder count to zero.",
            inputSchema={'type': 'object', 'properties': {'encoder_id': {'type': 'integer', 'description': 'Encoder ID'}}, 'required': ['encoder_id']},
        ),
        Tool(
            name="mara_imu_read",
            description="Read IMU sensor data (accelerometer and gyroscope).",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_ultrasonic_attach",
            description="Attach an ultrasonic distance sensor to GPIO pins.",
            inputSchema={'type': 'object', 'properties': {'sensor_id': {'type': 'integer', 'description': 'Sensor ID (0-3)'}, 'trig_pin': {'type': 'integer', 'description': 'Trigger GPIO pin'}, 'echo_pin': {'type': 'integer', 'description': 'Echo GPIO pin'}, 'max_distance_cm': {'type': 'number', 'description': 'Maximum measurable distance in cm', 'default': 400.0}}, 'required': ['sensor_id', 'trig_pin', 'echo_pin']},
        ),
        Tool(
            name="mara_ultrasonic_read",
            description="Read distance from ultrasonic sensor in centimeters.",
            inputSchema={'type': 'object', 'properties': {'sensor_id': {'type': 'integer', 'description': 'Sensor ID (0-3)'}}, 'required': ['sensor_id']},
        ),
        Tool(
            name="mara_ultrasonic_detach",
            description="Detach an ultrasonic sensor.",
            inputSchema={'type': 'object', 'properties': {'sensor_id': {'type': 'integer', 'description': 'Sensor ID (0-3)'}}, 'required': ['sensor_id']},
        ),
        Tool(
            name="mara_robot_describe",
            description="Get robot structure: joints, their limits, relationships, and what each controls. Call this first to understand what you're controlling.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_robot_state",
            description="Get complete robot status: safety state (IDLE/ARMED/ESTOP), current joint positions with freshness indicators, and sensor readings.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_robot_pose",
            description="Get current position of all joints by name, with percentage of range and freshness indicators.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_robot_move",
            description="Move one or more joints by name. Joints move simultaneously. Provide moves as JSON array.",
            inputSchema={'type': 'object', 'properties': {'moves': {'type': 'string', 'description': 'JSON array of moves, e.g. [{joint: shoulder, angle: 45}]'}, 'duration_ms': {'type': 'integer', 'description': 'Movement duration in milliseconds', 'default': 300}}, 'required': ['moves']},
        ),
        Tool(
            name="mara_robot_home",
            description="Move all joints (or specified joints) to their home positions.",
            inputSchema={'type': 'object', 'properties': {'joints': {'type': 'string', 'description': 'JSON array of joint names to home, or omit for all joints'}, 'duration_ms': {'type': 'integer', 'description': 'Movement duration in milliseconds', 'default': 500}}},
        ),
    ]


async def dispatch_tool(runtime, name: str, args: dict[str, Any]) -> str:
    """Execute a tool by name and return result string."""

    if name == "mara_connect":
        return await _handle_connect(runtime, args)

    if name == "mara_disconnect":
        return await _handle_disconnect(runtime, args)

    if name == "mara_get_state":
        return await _handle_get_state(runtime, args)

    if name == "mara_get_freshness":
        return await _handle_get_freshness(runtime, args)

    if name == "mara_get_events":
        return await _handle_get_events(runtime, args)

    if name == "mara_get_command_stats":
        return await _handle_get_command_stats(runtime, args)

    if name == "mara_wifi_status":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.wifi_service.status()
        runtime.record_command("wifi_status", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return str(result.data) if result.data else "wifi_status OK"
        return f"FAIL: {result.error}"

    if name == "mara_wifi_join":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.wifi_service.join(ssid=args["ssid"], password=args["password"], wait_for_connect=args.get("wait_for_connect", True), timeout_ms=args.get("timeout_ms", 10000))
        runtime.record_command("wifi_join", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return str(result.data) if result.data else "wifi_join OK"
        return f"FAIL: {result.error}"

    if name == "mara_wifi_disconnect":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.wifi_service.disconnect()
        runtime.record_command("wifi_disconnect", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return str(result.data) if result.data else "wifi_disconnect OK"
        return f"FAIL: {result.error}"

    if name == "mara_arm":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.state_service.arm()
        runtime.sync_state_result(result)
        runtime.record_command("arm", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Armed".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_disarm":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.state_service.disarm()
        runtime.sync_state_result(result)
        runtime.record_command("disarm", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Disarmed".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_stop":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.state_service.stop()
        runtime.sync_state_result(result)
        runtime.record_command("stop", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Stopped".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_servo_attach":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.servo_service.attach(servo_id=args["servo_id"], channel=args["pin"], min_us=args.get("min_us", 500), max_us=args.get("max_us", 2500))
        runtime.record_command("servo_attach", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Servo {servo_id} attached to pin {pin}".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_servo_set":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.servo_service.set_angle(servo_id=args["servo_id"], angle=args["angle"], duration_ms=args.get("duration_ms", 300))
        runtime.record_command("servo_set", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Servo {servo_id} -> {angle}deg".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_servo_center":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.servo_service.center(servo_id=args["servo_id"])
        runtime.record_command("servo_center", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Servo {servo_id} centered".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_servo_detach":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.servo_service.detach(servo_id=args["servo_id"])
        runtime.record_command("servo_detach", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Servo {servo_id} detached".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_motor_set":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.motor_service.set_speed(motor_id=args["motor_id"], speed=args["speed"])
        runtime.record_command("motor_set", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Motor {motor_id} -> {speed:.0%}".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_motor_stop":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.motor_service.stop(motor_id=args["motor_id"])
        runtime.record_command("motor_stop", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Motor {motor_id} stopped".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_gpio_write":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.gpio_service.write(channel=args["channel"], value=args["value"])
        runtime.record_command("gpio_write", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "GPIO {channel} set to {value}".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_gpio_toggle":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.gpio_service.toggle(channel=args["channel"])
        runtime.record_command("gpio_toggle", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "GPIO {channel} toggled".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_gpio_read":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.gpio_service.read(channel=args["channel"])
        runtime.record_command("gpio_read", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return str(result.data) if result.data else "gpio_read OK"
        return f"FAIL: {result.error}"

    if name == "mara_stepper_move":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.stepper_service.move_relative(stepper_id=args["stepper_id"], steps=args["steps"], speed=args.get("speed", None))
        runtime.record_command("stepper_move", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Stepper {stepper_id} moved {steps} steps".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_stepper_stop":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.stepper_service.stop(stepper_id=args["stepper_id"])
        runtime.record_command("stepper_stop", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Stepper {stepper_id} stopped".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_pwm_set":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.pwm_service.set_duty(channel=args["channel"], duty=args["duty"])
        runtime.record_command("pwm_set", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "PWM {channel} -> {duty:.0%}".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_encoder_read":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.encoder_service.read(encoder_id=args["encoder_id"])
        runtime.record_command("encoder_read", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return str(result.data) if result.data else "encoder_read OK"
        return f"FAIL: {result.error}"

    if name == "mara_encoder_reset":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.encoder_service.reset(encoder_id=args["encoder_id"])
        runtime.record_command("encoder_reset", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Encoder {encoder_id} reset".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_imu_read":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.imu_service.read()
        runtime.record_command("imu_read", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return str(result.data) if result.data else "imu_read OK"
        return f"FAIL: {result.error}"

    if name == "mara_ultrasonic_attach":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.ultrasonic_service.attach(sensor_id=args["sensor_id"], trig_pin=args["trig_pin"], echo_pin=args["echo_pin"], max_distance_cm=args.get("max_distance_cm", 400.0))
        runtime.record_command("ultrasonic_attach", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Ultrasonic {sensor_id} attached (trig={trig_pin}, echo={echo_pin})".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_ultrasonic_read":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.ultrasonic_service.read(sensor_id=args["sensor_id"])
        runtime.record_command("ultrasonic_read", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return str(result.data) if result.data else "ultrasonic_read OK"
        return f"FAIL: {result.error}"

    if name == "mara_ultrasonic_detach":
        await runtime.ensure_connected()
        sent_at = datetime.now()
        result = await runtime.ultrasonic_service.detach(sensor_id=args["sensor_id"])
        runtime.record_command("ultrasonic_detach", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Ultrasonic {sensor_id} detached".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_robot_describe":
        return await _handle_robot_describe(runtime, args)

    if name == "mara_robot_state":
        return await _handle_robot_state(runtime, args)

    if name == "mara_robot_pose":
        return await _handle_robot_pose(runtime, args)

    if name == "mara_robot_move":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.robot_service.move_joints(moves=args["moves"], duration_ms=args.get("duration_ms", 300))
        runtime.record_command("robot_move", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Moved: {moved}".format(**args)
        return f"FAIL: {result.error}"

    if name == "mara_robot_home":
        await runtime.ensure_armed()
        sent_at = datetime.now()
        result = await runtime.robot_service.home(joints=args.get("joints", None), duration_ms=args.get("duration_ms", 500))
        runtime.record_command("robot_home", args, result.ok, result.error, sent_at=sent_at)
        if result.ok:
            return "Homed".format(**args)
        return f"FAIL: {result.error}"

    return f"Unknown tool: {name}"


# Custom handlers for special tools
async def _handle_connect(runtime, args: dict) -> str:
    result = await runtime.connect()
    return f"Connected: {result}"


async def _handle_disconnect(runtime, args: dict) -> str:
    result = await runtime.disconnect()
    return f"Disconnected: {result}"


async def _handle_get_state(runtime, args: dict) -> str:
    if not runtime.is_connected:
        return "Not connected. Use mara_connect first."
    return str(runtime.get_snapshot())


async def _handle_get_freshness(runtime, args: dict) -> str:
    if not runtime.is_connected:
        return "Not connected. Use mara_connect first."
    return str(runtime.get_freshness_report())


async def _handle_get_events(runtime, args: dict) -> str:
    if not runtime.is_connected:
        return "Not connected. Use mara_connect first."
    events = runtime.state.get_recent_events(20)
    return str([e.to_dict() for e in events])


async def _handle_get_command_stats(runtime, args: dict) -> str:
    if not runtime.is_connected:
        return "Not connected. Use mara_connect first."
    return str(runtime.state.get_command_stats())


# Robot abstraction layer handlers
async def _handle_robot_describe(runtime, args: dict) -> str:
    if not runtime.robot_loaded:
        return "Robot not loaded. Call load_robot(config_path) first."
    return runtime.robot_service.describe()


async def _handle_robot_state(runtime, args: dict) -> str:
    if not runtime.robot_loaded:
        return "Robot not loaded. Call load_robot(config_path) first."
    return runtime.robot_context.get_state_summary()


async def _handle_robot_pose(runtime, args: dict) -> str:
    if not runtime.robot_loaded:
        return "Robot not loaded. Call load_robot(config_path) first."
    return runtime.robot_context.format_pose()
