# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: tools/gen_mcp_servers.py
# Generated at: 2026-03-22T09:47:54.493333
"""
Generated MCP tool definitions and dispatch.
"""

from __future__ import annotations

from typing import Any
from mcp.types import Tool, TextContent


def get_tool_definitions() -> list[Tool]:
    """Return list of MCP Tool definitions."""
    return [
        Tool(
            name="mara_connect",
            description="Connect to the robot. Auto-connects if needed for other commands.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_disconnect",
            description="Disconnect from the robot.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_get_state",
            description="Get current robot state including connection, arm status, telemetry, and recent commands.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_arm",
            description="Arm the robot for operation. Required before moving actuators.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_disarm",
            description="Disarm the robot. Stops all motion.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_stop",
            description="Emergency stop - immediately halt all motion.",
            inputSchema={'type': 'object', 'properties': {}},
        ),
        Tool(
            name="mara_servo_attach",
            description="Attach a servo to a GPIO pin.",
            inputSchema={'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}, 'pin': {'type': 'integer', 'description': 'GPIO pin number'}, 'min_us': {'type': 'integer', 'description': 'Min pulse width in microseconds', 'default': 500}, 'max_us': {'type': 'integer', 'description': 'Max pulse width in microseconds', 'default': 2500}}, 'required': ['servo_id', 'pin']},
        ),
        Tool(
            name="mara_servo_set",
            description="Move a servo to the specified angle.",
            inputSchema={'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}, 'angle': {'type': 'number', 'description': 'Angle in degrees (0-180)'}, 'duration_ms': {'type': 'integer', 'description': 'Movement duration in ms (0=instant)', 'default': 300}}, 'required': ['servo_id', 'angle']},
        ),
        Tool(
            name="mara_servo_center",
            description="Move servo to center position (90 degrees).",
            inputSchema={'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}}, 'required': ['servo_id']},
        ),
        Tool(
            name="mara_servo_detach",
            description="Detach a servo from its pin.",
            inputSchema={'type': 'object', 'properties': {'servo_id': {'type': 'integer', 'description': 'Servo ID (0-7)'}}, 'required': ['servo_id']},
        ),
        Tool(
            name="mara_motor_set",
            description="Set DC motor speed.",
            inputSchema={'type': 'object', 'properties': {'motor_id': {'type': 'integer', 'description': 'Motor ID (0-3)'}, 'speed': {'type': 'number', 'description': 'Speed (-1.0 to 1.0)'}}, 'required': ['motor_id', 'speed']},
        ),
        Tool(
            name="mara_motor_stop",
            description="Stop a DC motor.",
            inputSchema={'type': 'object', 'properties': {'motor_id': {'type': 'integer', 'description': 'Motor ID (0-3)'}}, 'required': ['motor_id']},
        ),
        Tool(
            name="mara_gpio_write",
            description="Set GPIO pin high or low.",
            inputSchema={'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}, 'value': {'type': 'integer', 'description': '0=low, 1=high'}}, 'required': ['channel', 'value']},
        ),
        Tool(
            name="mara_gpio_toggle",
            description="Toggle GPIO pin state.",
            inputSchema={'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}}, 'required': ['channel']},
        ),
        Tool(
            name="mara_gpio_read",
            description="Read GPIO pin state.",
            inputSchema={'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'GPIO channel ID'}}, 'required': ['channel']},
        ),
        Tool(
            name="mara_stepper_move",
            description="Move stepper motor by relative steps.",
            inputSchema={'type': 'object', 'properties': {'stepper_id': {'type': 'integer', 'description': 'Stepper ID'}, 'steps': {'type': 'integer', 'description': 'Steps to move (negative=reverse)'}, 'speed': {'type': 'number', 'description': 'Speed in steps/second'}}, 'required': ['stepper_id', 'steps']},
        ),
        Tool(
            name="mara_stepper_stop",
            description="Stop a stepper motor.",
            inputSchema={'type': 'object', 'properties': {'stepper_id': {'type': 'integer', 'description': 'Stepper ID'}}, 'required': ['stepper_id']},
        ),
        Tool(
            name="mara_pwm_set",
            description="Set PWM duty cycle on a channel.",
            inputSchema={'type': 'object', 'properties': {'channel': {'type': 'integer', 'description': 'PWM channel'}, 'duty': {'type': 'number', 'description': 'Duty cycle (0.0-1.0)'}}, 'required': ['channel', 'duty']},
        ),
        Tool(
            name="mara_encoder_read",
            description="Read encoder value.",
            inputSchema={'type': 'object', 'properties': {'encoder_id': {'type': 'integer', 'description': 'Encoder ID'}}, 'required': ['encoder_id']},
        ),
        Tool(
            name="mara_encoder_reset",
            description="Reset encoder count to zero.",
            inputSchema={'type': 'object', 'properties': {'encoder_id': {'type': 'integer', 'description': 'Encoder ID'}}, 'required': ['encoder_id']},
        ),
        Tool(
            name="mara_imu_read",
            description="Read IMU sensor data (accelerometer and gyroscope).",
            inputSchema={'type': 'object', 'properties': {}},
        ),
    ]


async def dispatch_tool(runtime, name: str, args: dict[str, Any]) -> str:
    """Execute a tool by name and return result string."""

    if name == "mara_connect":
        return await _handle_connect(runtime, args)

    if name == "mara_disconnect":
        return await _handle_disconnect(runtime, args)

    if name == "mara_get_state":
        return await _handle_get_state(runtime, args)

    if name == "mara_arm":
        await runtime.ensure_connected()
        ok, err = await runtime.client.arm()
        runtime.record_command("arm", {}, ok, err)
        return "OK: Armed" if ok else f"FAIL: {err}"

    if name == "mara_disarm":
        await runtime.ensure_connected()
        ok, err = await runtime.client.disarm()
        runtime.record_command("disarm", {}, ok, err)
        return "OK: Disarmed" if ok else f"FAIL: {err}"

    if name == "mara_stop":
        await runtime.ensure_connected()
        ok, err = await runtime.client.cmd_stop()
        runtime.record_command("stop", {}, ok, err)
        return "OK: Stopped" if ok else f"FAIL: {err}"

    if name == "mara_servo_attach":
        await runtime.ensure_armed()
        result = await runtime.servo_service.attach(servo_id=args["servo_id"], channel=args["pin"], min_us=args.get("min_us", 500), max_us=args.get("max_us", 2500))
        runtime.record_command("servo_attach", args, result.ok, result.error)
        if result.ok:
            return f"Servo {servo_id} attached to pin {pin}"
        return f"FAIL: {result.error}"

    if name == "mara_servo_set":
        await runtime.ensure_armed()
        result = await runtime.servo_service.set_angle(servo_id=args["servo_id"], angle=args["angle"], duration_ms=args.get("duration_ms", 300))
        runtime.record_command("servo_set", args, result.ok, result.error)
        if result.ok:
            return f"Servo {servo_id} -> {angle}deg"
        return f"FAIL: {result.error}"

    if name == "mara_servo_center":
        await runtime.ensure_armed()
        result = await runtime.servo_service.center(servo_id=args["servo_id"])
        runtime.record_command("servo_center", args, result.ok, result.error)
        if result.ok:
            return f"Servo {servo_id} centered"
        return f"FAIL: {result.error}"

    if name == "mara_servo_detach":
        await runtime.ensure_armed()
        result = await runtime.servo_service.detach(servo_id=args["servo_id"])
        runtime.record_command("servo_detach", args, result.ok, result.error)
        if result.ok:
            return f"Servo {servo_id} detached"
        return f"FAIL: {result.error}"

    if name == "mara_motor_set":
        await runtime.ensure_armed()
        result = await runtime.motor_service.set_speed(motor_id=args["motor_id"], speed=args["speed"])
        runtime.record_command("motor_set", args, result.ok, result.error)
        if result.ok:
            return f"Motor {motor_id} -> {speed:.0%}"
        return f"FAIL: {result.error}"

    if name == "mara_motor_stop":
        await runtime.ensure_armed()
        result = await runtime.motor_service.stop(motor_id=args["motor_id"])
        runtime.record_command("motor_stop", args, result.ok, result.error)
        if result.ok:
            return f"Motor {motor_id} stopped"
        return f"FAIL: {result.error}"

    if name == "mara_gpio_write":
        await runtime.ensure_armed()
        result = await runtime.gpio_service.write(channel=args["channel"], value=args["value"])
        runtime.record_command("gpio_write", args, result.ok, result.error)
        if result.ok:
            return f"GPIO {channel} -> {'HIGH' if value else 'LOW'}"
        return f"FAIL: {result.error}"

    if name == "mara_gpio_toggle":
        await runtime.ensure_armed()
        result = await runtime.gpio_service.toggle(channel=args["channel"])
        runtime.record_command("gpio_toggle", args, result.ok, result.error)
        if result.ok:
            return f"GPIO {channel} toggled"
        return f"FAIL: {result.error}"

    if name == "mara_gpio_read":
        await runtime.ensure_connected()
        result = await runtime.gpio_service.read(channel=args["channel"])
        runtime.record_command("gpio_read", args, result.ok, result.error)
        if result.ok:
            return str(result.data) if result.data else "gpio_read OK"
        return f"FAIL: {result.error}"

    if name == "mara_stepper_move":
        await runtime.ensure_armed()
        result = await runtime.stepper_service.move_relative(stepper_id=args["stepper_id"], steps=args["steps"], speed=args.get("speed", None))
        runtime.record_command("stepper_move", args, result.ok, result.error)
        if result.ok:
            return f"Stepper {stepper_id} moved {steps} steps"
        return f"FAIL: {result.error}"

    if name == "mara_stepper_stop":
        await runtime.ensure_armed()
        result = await runtime.stepper_service.stop(stepper_id=args["stepper_id"])
        runtime.record_command("stepper_stop", args, result.ok, result.error)
        if result.ok:
            return f"Stepper {stepper_id} stopped"
        return f"FAIL: {result.error}"

    if name == "mara_pwm_set":
        await runtime.ensure_armed()
        result = await runtime.pwm_service.set_duty(channel=args["channel"], duty=args["duty"])
        runtime.record_command("pwm_set", args, result.ok, result.error)
        if result.ok:
            return f"PWM {channel} -> {duty:.0%}"
        return f"FAIL: {result.error}"

    if name == "mara_encoder_read":
        await runtime.ensure_connected()
        result = await runtime.encoder_service.read(encoder_id=args["encoder_id"])
        runtime.record_command("encoder_read", args, result.ok, result.error)
        if result.ok:
            return str(result.data) if result.data else "encoder_read OK"
        return f"FAIL: {result.error}"

    if name == "mara_encoder_reset":
        await runtime.ensure_armed()
        result = await runtime.encoder_service.reset(encoder_id=args["encoder_id"])
        runtime.record_command("encoder_reset", args, result.ok, result.error)
        if result.ok:
            return f"Encoder {encoder_id} reset"
        return f"FAIL: {result.error}"

    if name == "mara_imu_read":
        await runtime.ensure_connected()
        result = await runtime.imu_service.read()
        runtime.record_command("imu_read", args, result.ok, result.error)
        if result.ok:
            return str(result.data) if result.data else "imu_read OK"
        return f"FAIL: {result.error}"

    return f"Unknown tool: {name}"


# Custom handlers for special tools
async def _handle_connect(runtime, args: dict) -> str:
    result = await runtime.connect()
    return f"Connected: {result}"


async def _handle_disconnect(runtime, args: dict) -> str:
    result = await runtime.disconnect()
    return f"Disconnected: {result}"


async def _handle_get_state(runtime, args: dict) -> str:
    if not runtime.is_connected:
        return "Not connected. Use mara_connect first."
    return str(runtime.get_snapshot())
