# AUTO-GENERATED BY gen_commands.py — DO NOT EDIT.

from __future__ import annotations
from typing import Any, Optional


class RobotCommandsMixin:
    """
    Auto-generated high-level JSON command helpers.
    Requires that the inheriting client defines:
        async def send_json_cmd(self, type_str: str, payload: dict | None = None) -> None
    """
    async def cmd_bench_start(self, test_id: int, iterations: int = 100, warmup: int = 10, budget_us: int = 0, rt_safe: bool = False, stream: bool = False) -> None:
        """Start a benchmark test on the MCU. (CMD_BENCH_START)"""
        payload: dict[str, Any] = {}
        payload['test_id'] = test_id
        payload['iterations'] = iterations
        payload['warmup'] = warmup
        payload['budget_us'] = budget_us
        payload['rt_safe'] = rt_safe
        payload['stream'] = stream
        await self.send_json_cmd('CMD_BENCH_START', payload)

    async def cmd_bench_stop(self) -> None:
        """Cancel all running and queued benchmarks. (CMD_BENCH_STOP)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_BENCH_STOP', payload)

    async def cmd_bench_status(self) -> None:
        """Get current benchmark system status. (CMD_BENCH_STATUS)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_BENCH_STATUS', payload)

    async def cmd_bench_list_tests(self) -> None:
        """List all available benchmark tests. (CMD_BENCH_LIST_TESTS)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_BENCH_LIST_TESTS', payload)

    async def cmd_bench_get_results(self, max: int = 4) -> None:
        """Get benchmark result history. (CMD_BENCH_GET_RESULTS)"""
        payload: dict[str, Any] = {}
        payload['max'] = max
        await self.send_json_cmd('CMD_BENCH_GET_RESULTS', payload)

    async def cmd_bench_run_boot_tests(self) -> None:
        """Manually trigger boot-time benchmark tests. (CMD_BENCH_RUN_BOOT_TESTS)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_BENCH_RUN_BOOT_TESTS', payload)

    async def cmd_perf_reset(self) -> None:
        """Reset MCU performance counters and statistics. (CMD_PERF_RESET)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_PERF_RESET', payload)

    async def cmd_cam_get_status(self, camera_id: int = 0) -> None:
        """Get camera device status (IP, RSSI, heap, uptime). (CMD_CAM_GET_STATUS)"""
        payload: dict[str, Any] = {}
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_GET_STATUS', payload)

    async def cmd_cam_get_config(self, camera_id: int = 0) -> None:
        """Get current camera configuration. (CMD_CAM_GET_CONFIG)"""
        payload: dict[str, Any] = {}
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_GET_CONFIG', payload)

    async def cmd_cam_set_resolution(self, size: int, camera_id: int = 0) -> None:
        """Set camera resolution. 5=QVGA(320x240), 8=VGA(640x480), 9=SVGA(800x600), 10=XGA(1024x768), 13=UXGA(1600x1200). (CMD_CAM_SET_RESOLUTION)"""
        payload: dict[str, Any] = {}
        payload['size'] = size
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_SET_RESOLUTION', payload)

    async def cmd_cam_set_quality(self, quality: int, camera_id: int = 0) -> None:
        """Set JPEG compression quality. Lower values = better quality, larger files. (CMD_CAM_SET_QUALITY)"""
        payload: dict[str, Any] = {}
        payload['quality'] = quality
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_SET_QUALITY', payload)

    async def cmd_cam_set_brightness(self, brightness: int, camera_id: int = 0) -> None:
        """Set image brightness. (CMD_CAM_SET_BRIGHTNESS)"""
        payload: dict[str, Any] = {}
        payload['brightness'] = brightness
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_SET_BRIGHTNESS', payload)

    async def cmd_cam_set_contrast(self, contrast: int, camera_id: int = 0) -> None:
        """Set image contrast. (CMD_CAM_SET_CONTRAST)"""
        payload: dict[str, Any] = {}
        payload['contrast'] = contrast
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_SET_CONTRAST', payload)

    async def cmd_cam_set_saturation(self, saturation: int, camera_id: int = 0) -> None:
        """Set color saturation. (CMD_CAM_SET_SATURATION)"""
        payload: dict[str, Any] = {}
        payload['saturation'] = saturation
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_SET_SATURATION', payload)

    async def cmd_cam_set_sharpness(self, sharpness: int, camera_id: int = 0) -> None:
        """Set image sharpness. (CMD_CAM_SET_SHARPNESS)"""
        payload: dict[str, Any] = {}
        payload['sharpness'] = sharpness
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_SET_SHARPNESS', payload)

    async def cmd_cam_set_flip(self, camera_id: int = 0, hmirror: bool = False, vflip: bool = False) -> None:
        """Set image flip/mirror options. (CMD_CAM_SET_FLIP)"""
        payload: dict[str, Any] = {}
        payload['camera_id'] = camera_id
        payload['hmirror'] = hmirror
        payload['vflip'] = vflip
        await self.send_json_cmd('CMD_CAM_SET_FLIP', payload)

    async def cmd_cam_set_awb(self, enabled: bool, camera_id: int = 0, mode: int = 0) -> None:
        """Configure auto white balance. (CMD_CAM_SET_AWB)"""
        payload: dict[str, Any] = {}
        payload['enabled'] = enabled
        payload['camera_id'] = camera_id
        payload['mode'] = mode
        await self.send_json_cmd('CMD_CAM_SET_AWB', payload)

    async def cmd_cam_set_exposure(self, auto: bool, camera_id: int = 0, value: int = 300) -> None:
        """Configure exposure settings. (CMD_CAM_SET_EXPOSURE)"""
        payload: dict[str, Any] = {}
        payload['auto'] = auto
        payload['camera_id'] = camera_id
        payload['value'] = value
        await self.send_json_cmd('CMD_CAM_SET_EXPOSURE', payload)

    async def cmd_cam_set_gain(self, auto: bool, camera_id: int = 0, value: int = 0, ceiling: int = 2) -> None:
        """Configure gain settings. (CMD_CAM_SET_GAIN)"""
        payload: dict[str, Any] = {}
        payload['auto'] = auto
        payload['camera_id'] = camera_id
        payload['value'] = value
        payload['ceiling'] = ceiling
        await self.send_json_cmd('CMD_CAM_SET_GAIN', payload)

    async def cmd_cam_flash(self, state: str, camera_id: int = 0) -> None:
        """Control flash LED. (CMD_CAM_FLASH)"""
        payload: dict[str, Any] = {}
        payload['state'] = state
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_FLASH', payload)

    async def cmd_cam_apply_preset(self, preset: str, camera_id: int = 0) -> None:
        """Apply a predefined camera configuration preset. (CMD_CAM_APPLY_PRESET)"""
        payload: dict[str, Any] = {}
        payload['preset'] = preset
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_APPLY_PRESET', payload)

    async def cmd_cam_start_capture(self, camera_id: int = 0, mode: str = 'polling', fps: float = 10.0) -> None:
        """Start continuous frame capture (polling or streaming mode). (CMD_CAM_START_CAPTURE)"""
        payload: dict[str, Any] = {}
        payload['camera_id'] = camera_id
        payload['mode'] = mode
        payload['fps'] = fps
        await self.send_json_cmd('CMD_CAM_START_CAPTURE', payload)

    async def cmd_cam_stop_capture(self, camera_id: int = 0) -> None:
        """Stop continuous frame capture. (CMD_CAM_STOP_CAPTURE)"""
        payload: dict[str, Any] = {}
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_STOP_CAPTURE', payload)

    async def cmd_cam_capture_frame(self, camera_id: int = 0, publish: bool = True) -> None:
        """Capture a single frame (one-shot). (CMD_CAM_CAPTURE_FRAME)"""
        payload: dict[str, Any] = {}
        payload['camera_id'] = camera_id
        payload['publish'] = publish
        await self.send_json_cmd('CMD_CAM_CAPTURE_FRAME', payload)

    async def cmd_cam_start_recording(self, camera_id: int = 0, output_dir: str = 'recordings', format: str = 'video') -> None:
        """Start recording frames to disk. (CMD_CAM_START_RECORDING)"""
        payload: dict[str, Any] = {}
        payload['camera_id'] = camera_id
        payload['output_dir'] = output_dir
        payload['format'] = format
        await self.send_json_cmd('CMD_CAM_START_RECORDING', payload)

    async def cmd_cam_stop_recording(self, camera_id: int = 0) -> None:
        """Stop recording. (CMD_CAM_STOP_RECORDING)"""
        payload: dict[str, Any] = {}
        payload['camera_id'] = camera_id
        await self.send_json_cmd('CMD_CAM_STOP_RECORDING', payload)

    async def cmd_cam_set_motion_detection(self, enabled: bool, camera_id: int = 0, sensitivity: int = 30) -> None:
        """Configure motion detection. (CMD_CAM_SET_MOTION_DETECTION)"""
        payload: dict[str, Any] = {}
        payload['enabled'] = enabled
        payload['camera_id'] = camera_id
        payload['sensitivity'] = sensitivity
        await self.send_json_cmd('CMD_CAM_SET_MOTION_DETECTION', payload)

    async def cmd_ctrl_signal_define(self, id: int, name: str, signal_kind: str, initial: float = 0.0) -> None:
        """Define a new signal in the signal bus. Only allowed when IDLE. (CMD_CTRL_SIGNAL_DEFINE)"""
        payload: dict[str, Any] = {}
        payload['id'] = id
        payload['name'] = name
        payload['signal_kind'] = signal_kind
        payload['initial'] = initial
        await self.send_json_cmd('CMD_CTRL_SIGNAL_DEFINE', payload)

    async def cmd_ctrl_signals_clear(self) -> None:
        """Clear all signals from the signal bus. (CMD_CTRL_SIGNALS_CLEAR)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_CTRL_SIGNALS_CLEAR', payload)

    async def cmd_ctrl_signal_set(self, id: int, value: float) -> None:
        """Set a signal value in the signal bus. (CMD_CTRL_SIGNAL_SET)"""
        payload: dict[str, Any] = {}
        payload['id'] = id
        payload['value'] = value
        await self.send_json_cmd('CMD_CTRL_SIGNAL_SET', payload)

    async def cmd_ctrl_signal_get(self, id: int) -> None:
        """Get a signal value from the signal bus. (CMD_CTRL_SIGNAL_GET)"""
        payload: dict[str, Any] = {}
        payload['id'] = id
        await self.send_json_cmd('CMD_CTRL_SIGNAL_GET', payload)

    async def cmd_ctrl_signals_list(self) -> None:
        """List all defined signals in the signal bus. (CMD_CTRL_SIGNALS_LIST)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_CTRL_SIGNALS_LIST', payload)

    async def cmd_ctrl_signal_delete(self, id: Optional[Any] = None) -> None:
        """Delete a signal from the signal bus. (CMD_CTRL_SIGNAL_DELETE)"""
        payload: dict[str, Any] = {}
        if id is not None:
            payload['id'] = id
        await self.send_json_cmd('CMD_CTRL_SIGNAL_DELETE', payload)

    async def cmd_ctrl_signal_trace(self, signal_ids: Optional[Any] = None, rate_hz: int = 10) -> None:
        """Subscribe to trace specific signals via telemetry at a configurable rate. (CMD_CTRL_SIGNAL_TRACE)"""
        payload: dict[str, Any] = {}
        if signal_ids is not None:
            payload['signal_ids'] = signal_ids
        payload['rate_hz'] = rate_hz
        await self.send_json_cmd('CMD_CTRL_SIGNAL_TRACE', payload)

    async def cmd_ctrl_auto_signals_config(self, imu: Optional[Any] = None, encoder: Optional[Any] = None) -> None:
        """Configure auto-signal publishing from hardware managers (IMU, encoders, etc). Requires ARMED state. (CMD_CTRL_AUTO_SIGNALS_CONFIG)"""
        payload: dict[str, Any] = {}
        if imu is not None:
            payload['imu'] = imu
        if encoder is not None:
            payload['encoder'] = encoder
        await self.send_json_cmd('CMD_CTRL_AUTO_SIGNALS_CONFIG', payload)

    async def cmd_ctrl_slot_config(self, slot: int, controller_type: str, rate_hz: int = 100, ref_id: Optional[int] = None, meas_id: Optional[int] = None, out_id: Optional[int] = None, num_states: int = 2, num_inputs: int = 1, state_ids: Optional[Any] = None, ref_ids: Optional[Any] = None, output_ids: Optional[Any] = None, require_armed: bool = True, require_active: bool = True) -> None:
        """Configure a control slot with controller type and signal routing. Only allowed when IDLE. (CMD_CTRL_SLOT_CONFIG)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['controller_type'] = controller_type
        payload['rate_hz'] = rate_hz
        if ref_id is not None:
            payload['ref_id'] = ref_id
        if meas_id is not None:
            payload['meas_id'] = meas_id
        if out_id is not None:
            payload['out_id'] = out_id
        payload['num_states'] = num_states
        payload['num_inputs'] = num_inputs
        if state_ids is not None:
            payload['state_ids'] = state_ids
        if ref_ids is not None:
            payload['ref_ids'] = ref_ids
        if output_ids is not None:
            payload['output_ids'] = output_ids
        payload['require_armed'] = require_armed
        payload['require_active'] = require_active
        await self.send_json_cmd('CMD_CTRL_SLOT_CONFIG', payload)

    async def cmd_ctrl_slot_enable(self, slot: int, enable: bool) -> None:
        """Enable or disable a configured control slot. (CMD_CTRL_SLOT_ENABLE)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['enable'] = enable
        await self.send_json_cmd('CMD_CTRL_SLOT_ENABLE', payload)

    async def cmd_ctrl_slot_get_param(self, slot: int, key: str) -> None:
        """Get a scalar parameter from a control slot's controller. (CMD_CTRL_SLOT_GET_PARAM)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['key'] = key
        await self.send_json_cmd('CMD_CTRL_SLOT_GET_PARAM', payload)

    async def cmd_ctrl_slot_reset(self, slot: int) -> None:
        """Reset a control slot's internal state (integrators, etc). (CMD_CTRL_SLOT_RESET)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        await self.send_json_cmd('CMD_CTRL_SLOT_RESET', payload)

    async def cmd_ctrl_slot_set_param(self, slot: int, key: str, value: float) -> None:
        """Set a scalar parameter on a control slot's controller. (CMD_CTRL_SLOT_SET_PARAM)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['key'] = key
        payload['value'] = value
        await self.send_json_cmd('CMD_CTRL_SLOT_SET_PARAM', payload)

    async def cmd_ctrl_slot_set_param_array(self, slot: int, key: str, values: Any) -> None:
        """Set an array parameter on a control slot (e.g., gain matrix K for state-space). (CMD_CTRL_SLOT_SET_PARAM_ARRAY)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['key'] = key
        payload['values'] = values
        await self.send_json_cmd('CMD_CTRL_SLOT_SET_PARAM_ARRAY', payload)

    async def cmd_ctrl_slot_status(self, slot: int) -> None:
        """Get status of a control slot. (CMD_CTRL_SLOT_STATUS)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        await self.send_json_cmd('CMD_CTRL_SLOT_STATUS', payload)

    async def cmd_ctrl_graph_upload(self, graph: Any, commit: bool = True, mode: str = 'replace') -> None:
        """Upload a runtime control-graph config. Use commit=false for two-phase commit (requires CMD_CTRL_GRAPH_COMMIT to activate). (CMD_CTRL_GRAPH_UPLOAD)"""
        payload: dict[str, Any] = {}
        payload['graph'] = graph
        payload['commit'] = commit
        payload['mode'] = mode
        await self.send_json_cmd('CMD_CTRL_GRAPH_UPLOAD', payload)

    async def cmd_ctrl_graph_clear(self) -> None:
        """Clear the stored runtime control-graph config. (CMD_CTRL_GRAPH_CLEAR)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_CTRL_GRAPH_CLEAR', payload)

    async def cmd_ctrl_graph_enable(self, enable: bool) -> None:
        """Enable or disable all stored control-graph slots. (CMD_CTRL_GRAPH_ENABLE)"""
        payload: dict[str, Any] = {}
        payload['enable'] = enable
        await self.send_json_cmd('CMD_CTRL_GRAPH_ENABLE', payload)

    async def cmd_ctrl_graph_status(self) -> None:
        """Get status of the stored runtime control graph. (CMD_CTRL_GRAPH_STATUS)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_CTRL_GRAPH_STATUS', payload)

    async def cmd_ctrl_graph_debug(self, slot_id: str) -> None:
        """Enable debug streaming for a single slot to see intermediate transform values. Only one slot can be in debug mode at a time. (CMD_CTRL_GRAPH_DEBUG)"""
        payload: dict[str, Any] = {}
        payload['slot_id'] = slot_id
        await self.send_json_cmd('CMD_CTRL_GRAPH_DEBUG', payload)

    async def cmd_ctrl_graph_commit(self, token: int) -> None:
        """Commit a pending control graph upload. Use with CMD_CTRL_GRAPH_UPLOAD commit=false for two-phase commit. (CMD_CTRL_GRAPH_COMMIT)"""
        payload: dict[str, Any] = {}
        payload['token'] = token
        await self.send_json_cmd('CMD_CTRL_GRAPH_COMMIT', payload)

    async def cmd_mcu_diagnostics_query(self) -> None:
        """Query persisted MCU diagnostics and mirrored persistence metadata. (CMD_MCU_DIAGNOSTICS_QUERY)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_MCU_DIAGNOSTICS_QUERY', payload)

    async def cmd_mcu_diagnostics_reset(self) -> None:
        """Reset persisted MCU diagnostics counters while preserving boot identity fields. (CMD_MCU_DIAGNOSTICS_RESET)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_MCU_DIAGNOSTICS_RESET', payload)

    async def cmd_dc_set_speed(self, motor_id: int, speed: float) -> None:
        """Set DC motor speed. (CMD_DC_SET_SPEED)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        payload['speed'] = speed
        await self.send_json_cmd('CMD_DC_SET_SPEED', payload)

    async def cmd_dc_stop(self, motor_id: int) -> None:
        """Stop a DC motor. (CMD_DC_STOP)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        await self.send_json_cmd('CMD_DC_STOP', payload)

    async def cmd_dc_vel_pid_enable(self, motor_id: int, enable: bool) -> None:
        """Enable or disable closed-loop velocity PID control for a DC motor. (CMD_DC_VEL_PID_ENABLE)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        payload['enable'] = enable
        await self.send_json_cmd('CMD_DC_VEL_PID_ENABLE', payload)

    async def cmd_dc_set_vel_target(self, motor_id: int, omega: float) -> None:
        """Set velocity target for a DC motor's PID controller. (CMD_DC_SET_VEL_TARGET)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        payload['omega'] = omega
        await self.send_json_cmd('CMD_DC_SET_VEL_TARGET', payload)

    async def cmd_dc_set_vel_gains(self, motor_id: int, kp: float, ki: float, kd: float) -> None:
        """Configure PID gains for DC motor velocity control. (CMD_DC_SET_VEL_GAINS)"""
        payload: dict[str, Any] = {}
        payload['motor_id'] = motor_id
        payload['kp'] = kp
        payload['ki'] = ki
        payload['kd'] = kd
        await self.send_json_cmd('CMD_DC_SET_VEL_GAINS', payload)

    async def cmd_led_on(self) -> None:
        """Turn status LED on. (CMD_LED_ON)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_LED_ON', payload)

    async def cmd_led_off(self) -> None:
        """Turn status LED off. (CMD_LED_OFF)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_LED_OFF', payload)

    async def cmd_gpio_write(self, channel: int, value: int) -> None:
        """Set GPIO pin high or low. (CMD_GPIO_WRITE)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        payload['value'] = value
        await self.send_json_cmd('CMD_GPIO_WRITE', payload)

    async def cmd_gpio_read(self, channel: int) -> None:
        """Read GPIO pin state. (CMD_GPIO_READ)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        await self.send_json_cmd('CMD_GPIO_READ', payload)

    async def cmd_gpio_toggle(self, channel: int) -> None:
        """Toggle GPIO pin state. (CMD_GPIO_TOGGLE)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        await self.send_json_cmd('CMD_GPIO_TOGGLE', payload)

    async def cmd_gpio_register_channel(self, channel: int, pin: int, mode: str = 'output') -> None:
        """Register a GPIO channel mapping a logical ID to a physical pin. (CMD_GPIO_REGISTER_CHANNEL)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        payload['pin'] = pin
        payload['mode'] = mode
        await self.send_json_cmd('CMD_GPIO_REGISTER_CHANNEL', payload)

    async def cmd_pwm_set(self, channel: int, duty: float, freq_hz: Optional[float] = None) -> None:
        """Set PWM duty cycle on a channel. (CMD_PWM_SET)"""
        payload: dict[str, Any] = {}
        payload['channel'] = channel
        payload['duty'] = duty
        if freq_hz is not None:
            payload['freq_hz'] = freq_hz
        await self.send_json_cmd('CMD_PWM_SET', payload)

    async def cmd_set_mode(self, mode: str) -> None:
        """Set the high-level robot mode. Prefer ARM/ACTIVATE/DISARM/DEACTIVATE. (CMD_SET_MODE)"""
        payload: dict[str, Any] = {}
        payload['mode'] = mode
        await self.send_json_cmd('CMD_SET_MODE', payload)

    async def cmd_set_vel(self, vx: float, omega: float, frame: str = 'robot') -> None:
        """Set linear and angular velocity in robot frame. (CMD_SET_VEL)"""
        payload: dict[str, Any] = {}
        payload['vx'] = vx
        payload['omega'] = omega
        payload['frame'] = frame
        await self.send_json_cmd('CMD_SET_VEL', payload)

    async def cmd_observer_config(self, slot: int, num_states: int, num_outputs: int, input_ids: Any, output_ids: Any, estimate_ids: Any, num_inputs: int = 1, rate_hz: int = 200) -> None:
        """Configure a Luenberger state observer. (CMD_OBSERVER_CONFIG)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['num_states'] = num_states
        payload['num_outputs'] = num_outputs
        payload['input_ids'] = input_ids
        payload['output_ids'] = output_ids
        payload['estimate_ids'] = estimate_ids
        payload['num_inputs'] = num_inputs
        payload['rate_hz'] = rate_hz
        await self.send_json_cmd('CMD_OBSERVER_CONFIG', payload)

    async def cmd_observer_enable(self, slot: int, enable: bool) -> None:
        """Enable or disable a configured observer. (CMD_OBSERVER_ENABLE)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['enable'] = enable
        await self.send_json_cmd('CMD_OBSERVER_ENABLE', payload)

    async def cmd_observer_reset(self, slot: int) -> None:
        """Reset observer state estimate to zero. (CMD_OBSERVER_RESET)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        await self.send_json_cmd('CMD_OBSERVER_RESET', payload)

    async def cmd_observer_set_param(self, slot: int, key: str, value: float) -> None:
        """Set individual matrix element (e.g., 'A01', 'L10'). (CMD_OBSERVER_SET_PARAM)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['key'] = key
        payload['value'] = value
        await self.send_json_cmd('CMD_OBSERVER_SET_PARAM', payload)

    async def cmd_observer_set_param_array(self, slot: int, key: str, values: Any) -> None:
        """Set full matrix (A, B, C, or L) in row-major order. (CMD_OBSERVER_SET_PARAM_ARRAY)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        payload['key'] = key
        payload['values'] = values
        await self.send_json_cmd('CMD_OBSERVER_SET_PARAM_ARRAY', payload)

    async def cmd_observer_status(self, slot: int) -> None:
        """Get observer status and current state estimates. (CMD_OBSERVER_STATUS)"""
        payload: dict[str, Any] = {}
        payload['slot'] = slot
        await self.send_json_cmd('CMD_OBSERVER_STATUS', payload)

    async def cmd_get_rates(self) -> None:
        """Get current loop rates (ctrl, safety, telem) in Hz. (CMD_GET_RATES)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_GET_RATES', payload)

    async def cmd_ctrl_set_rate(self, hz: int) -> None:
        """Set control loop rate in Hz. Only allowed when IDLE. (CMD_CTRL_SET_RATE)"""
        payload: dict[str, Any] = {}
        payload['hz'] = hz
        await self.send_json_cmd('CMD_CTRL_SET_RATE', payload)

    async def cmd_safety_set_rate(self, hz: int) -> None:
        """Set safety loop rate in Hz. Only allowed when IDLE. (CMD_SAFETY_SET_RATE)"""
        payload: dict[str, Any] = {}
        payload['hz'] = hz
        await self.send_json_cmd('CMD_SAFETY_SET_RATE', payload)

    async def cmd_telem_set_rate(self, hz: int) -> None:
        """Set telemetry loop rate in Hz. Only allowed when IDLE. (CMD_TELEM_SET_RATE)"""
        payload: dict[str, Any] = {}
        payload['hz'] = hz
        await self.send_json_cmd('CMD_TELEM_SET_RATE', payload)

    async def cmd_get_identity(self) -> None:
        """Get firmware version, board type, and feature flags. (CMD_GET_IDENTITY)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_GET_IDENTITY', payload)

    async def cmd_heartbeat(self) -> None:
        """Host heartbeat to maintain connection. Resets host timeout watchdog. (CMD_HEARTBEAT)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_HEARTBEAT', payload)

    async def cmd_arm(self) -> None:
        """Arm the robot for operation. Required before moving actuators. (CMD_ARM)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_ARM', payload)

    async def cmd_disarm(self) -> None:
        """Disarm the robot. Stops all motion. (CMD_DISARM)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_DISARM', payload)

    async def cmd_activate(self) -> None:
        """Activate the robot (ARMED -> ACTIVE). Motion commands are only accepted in ACTIVE state. (CMD_ACTIVATE)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_ACTIVATE', payload)

    async def cmd_deactivate(self) -> None:
        """Deactivate the robot (ACTIVE -> ARMED). Stops accepting motion commands. (CMD_DEACTIVATE)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_DEACTIVATE', payload)

    async def cmd_estop(self) -> None:
        """Emergency stop - immediately halt all motion and enter ESTOP state. Requires clear_estop before resuming. (CMD_ESTOP)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_ESTOP', payload)

    async def cmd_clear_estop(self) -> None:
        """Clear emergency stop condition (ESTOP -> IDLE). Required after estop before normal operation. (CMD_CLEAR_ESTOP)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_CLEAR_ESTOP', payload)

    async def cmd_stop(self) -> None:
        """Soft stop - zero velocities without changing robot state. (CMD_STOP)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_STOP', payload)

    async def cmd_get_state(self) -> None:
        """Query current robot state from MCU. Returns mode (IDLE/ARMED/ACTIVE/ESTOP), armed status, active status, and estop status. (CMD_GET_STATE)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_GET_STATE', payload)

    async def cmd_get_safety_timeouts(self) -> None:
        """Get safety timeout values. (CMD_GET_SAFETY_TIMEOUTS)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_GET_SAFETY_TIMEOUTS', payload)

    async def cmd_set_safety_timeouts(self, host_timeout_ms: Optional[int] = None, motion_timeout_ms: Optional[int] = None) -> None:
        """Set safety timeout values. Use 0 to disable a timeout. (CMD_SET_SAFETY_TIMEOUTS)"""
        payload: dict[str, Any] = {}
        if host_timeout_ms is not None:
            payload['host_timeout_ms'] = host_timeout_ms
        if motion_timeout_ms is not None:
            payload['motion_timeout_ms'] = motion_timeout_ms
        await self.send_json_cmd('CMD_SET_SAFETY_TIMEOUTS', payload)

    async def cmd_set_signing_key(self, key: Optional[str] = None, signature: Optional[str] = None) -> None:
        """Set the signing key for state transition authentication. First key allowed unconditionally. Key rotation requires current key signature. (CMD_SET_SIGNING_KEY)"""
        payload: dict[str, Any] = {}
        if key is not None:
            payload['key'] = key
        if signature is not None:
            payload['signature'] = signature
        await self.send_json_cmd('CMD_SET_SIGNING_KEY', payload)

    async def cmd_release_session(self, client_id: Optional[int] = None) -> None:
        """Release session ownership to allow another host to take control. (CMD_RELEASE_SESSION)"""
        payload: dict[str, Any] = {}
        if client_id is not None:
            payload['client_id'] = client_id
        await self.send_json_cmd('CMD_RELEASE_SESSION', payload)

    async def cmd_imu_read(self) -> None:
        """Read IMU sensor data (accelerometer and gyroscope). (CMD_IMU_READ)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_IMU_READ', payload)

    async def cmd_imu_calibrate(self, samples: int = 100, delay_ms: int = 10) -> None:
        """Auto-calibrate IMU bias by collecting samples. (CMD_IMU_CALIBRATE)"""
        payload: dict[str, Any] = {}
        payload['samples'] = samples
        payload['delay_ms'] = delay_ms
        await self.send_json_cmd('CMD_IMU_CALIBRATE', payload)

    async def cmd_imu_set_bias(self, accel_bias: Any, gyro_bias: Any) -> None:
        """Set IMU bias offsets manually. (CMD_IMU_SET_BIAS)"""
        payload: dict[str, Any] = {}
        payload['accel_bias'] = accel_bias
        payload['gyro_bias'] = gyro_bias
        await self.send_json_cmd('CMD_IMU_SET_BIAS', payload)

    async def cmd_imu_zero(self) -> None:
        """Reset IMU orientation (zero yaw/heading). (CMD_IMU_ZERO)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_IMU_ZERO', payload)

    async def cmd_i2c_scan(self) -> None:
        """Scan the MCU primary I2C bus and report responding addresses. (CMD_I2C_SCAN)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_I2C_SCAN', payload)

    async def cmd_ultrasonic_attach(self, sensor_id: int, trig_pin: int, echo_pin: int, max_distance_cm: float = 400.0) -> None:
        """Attach an ultrasonic distance sensor to GPIO pins. (CMD_ULTRASONIC_ATTACH)"""
        payload: dict[str, Any] = {}
        payload['sensor_id'] = sensor_id
        payload['trig_pin'] = trig_pin
        payload['echo_pin'] = echo_pin
        payload['max_distance_cm'] = max_distance_cm
        await self.send_json_cmd('CMD_ULTRASONIC_ATTACH', payload)

    async def cmd_ultrasonic_read(self, sensor_id: int) -> None:
        """Read distance from ultrasonic sensor in centimeters. (CMD_ULTRASONIC_READ)"""
        payload: dict[str, Any] = {}
        payload['sensor_id'] = sensor_id
        await self.send_json_cmd('CMD_ULTRASONIC_READ', payload)

    async def cmd_ultrasonic_detach(self, sensor_id: int) -> None:
        """Detach an ultrasonic sensor. (CMD_ULTRASONIC_DETACH)"""
        payload: dict[str, Any] = {}
        payload['sensor_id'] = sensor_id
        await self.send_json_cmd('CMD_ULTRASONIC_DETACH', payload)

    async def cmd_encoder_attach(self, encoder_id: int, pin_a: int, pin_b: int, ppr: int = 11, gear_ratio: float = 1.0) -> None:
        """Attach a quadrature encoder to GPIO pins. (CMD_ENCODER_ATTACH)"""
        payload: dict[str, Any] = {}
        payload['encoder_id'] = encoder_id
        payload['pin_a'] = pin_a
        payload['pin_b'] = pin_b
        payload['ppr'] = ppr
        payload['gear_ratio'] = gear_ratio
        await self.send_json_cmd('CMD_ENCODER_ATTACH', payload)

    async def cmd_encoder_read(self, encoder_id: int) -> None:
        """Read encoder value. (CMD_ENCODER_READ)"""
        payload: dict[str, Any] = {}
        payload['encoder_id'] = encoder_id
        await self.send_json_cmd('CMD_ENCODER_READ', payload)

    async def cmd_encoder_reset(self, encoder_id: int) -> None:
        """Reset encoder count to zero. (CMD_ENCODER_RESET)"""
        payload: dict[str, Any] = {}
        payload['encoder_id'] = encoder_id
        await self.send_json_cmd('CMD_ENCODER_RESET', payload)

    async def cmd_encoder_detach(self, encoder_id: int) -> None:
        """Detach an encoder. (CMD_ENCODER_DETACH)"""
        payload: dict[str, Any] = {}
        payload['encoder_id'] = encoder_id
        await self.send_json_cmd('CMD_ENCODER_DETACH', payload)

    async def cmd_servo_attach(self, servo_id: int, channel: int, min_us: int = 500, max_us: int = 2500) -> None:
        """Attach a servo to a GPIO pin. (CMD_SERVO_ATTACH)"""
        payload: dict[str, Any] = {}
        payload['servo_id'] = servo_id
        payload['channel'] = channel
        payload['min_us'] = min_us
        payload['max_us'] = max_us
        await self.send_json_cmd('CMD_SERVO_ATTACH', payload)

    async def cmd_servo_detach(self, servo_id: int) -> None:
        """Detach a servo from its pin. (CMD_SERVO_DETACH)"""
        payload: dict[str, Any] = {}
        payload['servo_id'] = servo_id
        await self.send_json_cmd('CMD_SERVO_DETACH', payload)

    async def cmd_servo_set_angle(self, servo_id: int, angle_deg: float, duration_ms: int = 300) -> None:
        """Move a servo to the specified angle. (CMD_SERVO_SET_ANGLE)"""
        payload: dict[str, Any] = {}
        payload['servo_id'] = servo_id
        payload['angle_deg'] = angle_deg
        payload['duration_ms'] = duration_ms
        await self.send_json_cmd('CMD_SERVO_SET_ANGLE', payload)

    async def cmd_servo_set_pulse(self, servo_id: int, pulse_us: int) -> None:
        """Set servo pulse width directly in microseconds. (CMD_SERVO_SET_PULSE)"""
        payload: dict[str, Any] = {}
        payload['servo_id'] = servo_id
        payload['pulse_us'] = pulse_us
        await self.send_json_cmd('CMD_SERVO_SET_PULSE', payload)

    async def cmd_batch_apply(self, actions: Any) -> None:
        """Apply a generic staged batch/composite envelope using actions=[{cmd,args}, ...]. Batchable commands: CMD_GPIO_WRITE, CMD_SERVO_SET_ANGLE, CMD_PWM_SET, CMD_DC_SET_SPEED, CMD_DC_STOP, CMD_STEPPER_MOVE_REL, CMD_STEPPER_STOP. MCU apply order is fixed by command family on one control tick. (CMD_BATCH_APPLY)"""
        payload: dict[str, Any] = {}
        payload['actions'] = actions
        await self.send_json_cmd('CMD_BATCH_APPLY', payload)

    async def cmd_stepper_enable(self, stepper_id: int, enable: bool = True) -> None:
        """Enable or disable a stepper driver (energize coils). (CMD_STEPPER_ENABLE)"""
        payload: dict[str, Any] = {}
        payload['stepper_id'] = stepper_id
        payload['enable'] = enable
        await self.send_json_cmd('CMD_STEPPER_ENABLE', payload)

    async def cmd_stepper_move_rel(self, stepper_id: int, steps: int, speed_rps: float = 1.0) -> None:
        """Move stepper motor by relative steps. (CMD_STEPPER_MOVE_REL)"""
        payload: dict[str, Any] = {}
        payload['stepper_id'] = stepper_id
        payload['steps'] = steps
        payload['speed_rps'] = speed_rps
        await self.send_json_cmd('CMD_STEPPER_MOVE_REL', payload)

    async def cmd_stepper_move_deg(self, stepper_id: int, degrees: float, speed_rps: float = 1.0) -> None:
        """Move stepper motor by degrees. (CMD_STEPPER_MOVE_DEG)"""
        payload: dict[str, Any] = {}
        payload['stepper_id'] = stepper_id
        payload['degrees'] = degrees
        payload['speed_rps'] = speed_rps
        await self.send_json_cmd('CMD_STEPPER_MOVE_DEG', payload)

    async def cmd_stepper_move_rev(self, stepper_id: int, revolutions: float, speed_rps: float = 1.0) -> None:
        """Move stepper motor by revolutions. (CMD_STEPPER_MOVE_REV)"""
        payload: dict[str, Any] = {}
        payload['stepper_id'] = stepper_id
        payload['revolutions'] = revolutions
        payload['speed_rps'] = speed_rps
        await self.send_json_cmd('CMD_STEPPER_MOVE_REV', payload)

    async def cmd_stepper_stop(self, stepper_id: int) -> None:
        """Stop a stepper motor. (CMD_STEPPER_STOP)"""
        payload: dict[str, Any] = {}
        payload['stepper_id'] = stepper_id
        await self.send_json_cmd('CMD_STEPPER_STOP', payload)

    async def cmd_stepper_get_position(self, stepper_id: int) -> None:
        """Get the current position of a stepper motor in steps. (CMD_STEPPER_GET_POSITION)"""
        payload: dict[str, Any] = {}
        payload['stepper_id'] = stepper_id
        await self.send_json_cmd('CMD_STEPPER_GET_POSITION', payload)

    async def cmd_stepper_reset_position(self, stepper_id: int) -> None:
        """Reset the stepper position counter to zero. (CMD_STEPPER_RESET_POSITION)"""
        payload: dict[str, Any] = {}
        payload['stepper_id'] = stepper_id
        await self.send_json_cmd('CMD_STEPPER_RESET_POSITION', payload)

    async def cmd_telem_set_interval(self, interval_ms: int = 100) -> None:
        """Set telemetry publish interval in milliseconds (0 = disable). (CMD_TELEM_SET_INTERVAL)"""
        payload: dict[str, Any] = {}
        payload['interval_ms'] = interval_ms
        await self.send_json_cmd('CMD_TELEM_SET_INTERVAL', payload)

    async def cmd_set_log_level(self, level: str = 'info') -> None:
        """Set MCU global logging verbosity level. (CMD_SET_LOG_LEVEL)"""
        payload: dict[str, Any] = {}
        payload['level'] = level
        await self.send_json_cmd('CMD_SET_LOG_LEVEL', payload)

    async def cmd_set_subsystem_log_level(self, subsystem: str, level: str = 'info') -> None:
        """Set logging verbosity for a specific MCU subsystem (e.g., servo, stepper, motor). (CMD_SET_SUBSYSTEM_LOG_LEVEL)"""
        payload: dict[str, Any] = {}
        payload['subsystem'] = subsystem
        payload['level'] = level
        await self.send_json_cmd('CMD_SET_SUBSYSTEM_LOG_LEVEL', payload)

    async def cmd_get_log_levels(self) -> None:
        """Get current MCU log levels (global and per-subsystem). (CMD_GET_LOG_LEVELS)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_GET_LOG_LEVELS', payload)

    async def cmd_clear_subsystem_log_levels(self) -> None:
        """Clear all per-subsystem log levels, reverting to global level. (CMD_CLEAR_SUBSYSTEM_LOG_LEVELS)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_CLEAR_SUBSYSTEM_LOG_LEVELS', payload)

    async def cmd_wifi_scan(self) -> None:
        """Scan for available WiFi networks. (CMD_WIFI_SCAN)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_WIFI_SCAN', payload)

    async def cmd_wifi_join(self, ssid: str, password: Optional[str] = None) -> None:
        """Connect to a WiFi network. (CMD_WIFI_JOIN)"""
        payload: dict[str, Any] = {}
        payload['ssid'] = ssid
        if password is not None:
            payload['password'] = password
        await self.send_json_cmd('CMD_WIFI_JOIN', payload)

    async def cmd_wifi_disconnect(self) -> None:
        """Disconnect from current WiFi network. (CMD_WIFI_DISCONNECT)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_WIFI_DISCONNECT', payload)

    async def cmd_wifi_status(self) -> None:
        """Get current WiFi connection status. (CMD_WIFI_STATUS)"""
        payload: dict[str, Any] = {}
        await self.send_json_cmd('CMD_WIFI_STATUS', payload)

