# AUTO-GENERATED FILE — DO NOT EDIT BY HAND
# Generated from mara_host.tools.schema.control_graph

from mara_host.tools.schema.control_graph.core import ParamDef, SinkDef, SourceDef, TransformDef

SCHEMA_VERSION = 1

SOURCE_KINDS = ['constant', 'imu_axis']
TRANSFORM_KINDS = ['abs', 'clamp', 'deadband', 'delta_gate', 'derivative', 'hysteresis', 'integrator', 'lowpass', 'map', 'median', 'negate', 'offset', 'oscillator', 'proportional', 'pulse', 'recall', 'scale', 'slew_rate', 'sum', 'tap', 'threshold', 'toggle']
SINK_KINDS = ['gpio_write', 'motor_speed', 'pwm_duty', 'servo_angle']
ALL_CONTROL_GRAPH_KINDS = ['abs', 'clamp', 'constant', 'deadband', 'delta_gate', 'derivative', 'gpio_write', 'hysteresis', 'imu_axis', 'integrator', 'lowpass', 'map', 'median', 'motor_speed', 'negate', 'offset', 'oscillator', 'proportional', 'pulse', 'pwm_duty', 'recall', 'scale', 'servo_angle', 'slew_rate', 'sum', 'tap', 'threshold', 'toggle']

CONTROL_GRAPH_SPEC_OBJECTS = {
    'abs': TransformDef(kind='abs', description='Output absolute value of input.', inputs=1, outputs=1, tags=('math',), impl_key='transform.abs'),
    'clamp': TransformDef(kind='clamp', description='Clamp the input signal to a configured range.', params=(ParamDef(name='min', type='float', description='Lower bound.', required=True, default=-1.0), ParamDef(name='max', type='float', description='Upper bound.', required=True, default=1.0),), inputs=1, outputs=1, tags=('math', 'safety'), impl_key='transform.clamp'),
    'constant': SourceDef(kind='constant', description='Publish a constant scalar value each tick.', params=(ParamDef(name='value', type='float', description='Constant scalar value to publish.', required=True, default=0.0),), outputs=1, tags=('utility',), impl_key='source.constant'),
    'deadband': TransformDef(kind='deadband', description='Suppress small input values around zero.', params=(ParamDef(name='threshold', type='float', description='Magnitude below which the output is forced to zero.', required=True, default=0.0, minimum=0.0),), inputs=1, outputs=1, tags=('nonlinear',), impl_key='transform.deadband'),
    'delta_gate': TransformDef(kind='delta_gate', description='Emit a new value only when it changes by at least a threshold from the last emitted value.', params=(ParamDef(name='threshold', type='float', description='Minimum absolute change required before a new value is emitted.', required=True, default=0.0, minimum=0.0),), inputs=1, outputs=1, stateful=True, tags=('stateful', 'gating'), impl_key='transform.delta_gate'),
    'derivative': TransformDef(kind='derivative', description='Compute rate of change of input (dv/dt). Useful for predictive/damping control.', params=(ParamDef(name='gain', type='float', description='Multiplier applied to the derivative output.', default=1.0),), inputs=1, outputs=1, stateful=True, tags=('control', 'math'), impl_key='transform.derivative'),
    'gpio_write': SinkDef(kind='gpio_write', description='Drive a logical GPIO output from a scalar signal.', params=(ParamDef(name='channel', type='int', description='Logical GPIO channel.', required=True, minimum=0),), inputs=1, requires=('gpio',), tags=('actuator',), impl_key='sink.gpio_write'),
    'hysteresis': TransformDef(kind='hysteresis', description='Schmitt trigger with separate on/off thresholds to prevent chattering.', params=(ParamDef(name='on_threshold', type='float', description='Threshold to turn on (input must exceed this to go high).', required=True, default=0.5), ParamDef(name='off_threshold', type='float', description='Threshold to turn off (input must drop below this to go low).', required=True, default=0.3),), inputs=1, outputs=1, stateful=True, tags=('logic', 'filter'), impl_key='transform.hysteresis'),
    'imu_axis': SourceDef(kind='imu_axis', description='Read a derived orientation axis from the IMU.', params=(ParamDef(name='axis', type='enum', description='Derived tilt axis to publish.', required=True, enum=['pitch', 'roll']),), outputs=1, requires=('imu',), tags=('sensor', 'orientation'), impl_key='source.imu_axis'),
    'integrator': TransformDef(kind='integrator', description='Accumulate input over time (integral). Includes anti-windup bounds.', params=(ParamDef(name='gain', type='float', description='Multiplier applied to input before integrating.', default=1.0), ParamDef(name='min', type='float', description='Anti-windup lower bound for accumulated value.', default=-1000.0), ParamDef(name='max', type='float', description='Anti-windup upper bound for accumulated value.', default=1000.0),), inputs=1, outputs=1, stateful=True, tags=('control', 'math'), impl_key='transform.integrator'),
    'lowpass': TransformDef(kind='lowpass', description='First-order exponential smoothing filter.', params=(ParamDef(name='alpha', type='float', description='Smoothing factor; higher tracks the input more aggressively.', required=True, default=0.5, minimum=0.0, maximum=1.0),), inputs=1, outputs=1, stateful=True, tags=('filter',), impl_key='transform.lowpass'),
    'map': TransformDef(kind='map', description='Linearly remap input from one range to another.', params=(ParamDef(name='in_min', type='float', description='Input range minimum.', required=True, default=0.0), ParamDef(name='in_max', type='float', description='Input range maximum.', required=True, default=1.0), ParamDef(name='out_min', type='float', description='Output range minimum.', required=True, default=0.0), ParamDef(name='out_max', type='float', description='Output range maximum.', required=True, default=1.0),), inputs=1, outputs=1, tags=('math', 'scaling'), impl_key='transform.map'),
    'median': TransformDef(kind='median', description='Rolling median filter (5-sample window). Rejects outlier spikes better than lowpass.', inputs=1, outputs=1, stateful=True, tags=('filter',), impl_key='transform.median'),
    'motor_speed': SinkDef(kind='motor_speed', description='Drive a DC motor speed command from a scalar signal.', params=(ParamDef(name='motor_id', type='int', description='Logical motor identifier.', required=True, minimum=0),), inputs=1, requires=('dc_motor',), tags=('actuator',), impl_key='sink.motor_speed'),
    'negate': TransformDef(kind='negate', description='Flip the sign of the input value.', inputs=1, outputs=1, tags=('math',), impl_key='transform.negate'),
    'offset': TransformDef(kind='offset', description='Add a constant offset to the input signal.', params=(ParamDef(name='value', type='float', description='Constant value added to the input.', required=True, default=0.0),), inputs=1, outputs=1, tags=('math',), impl_key='transform.offset'),
    'oscillator': TransformDef(kind='oscillator', description='Generate sine wave output. Input is ignored; output is offset + amplitude * sin(phase).', params=(ParamDef(name='frequency', type='float', description='Oscillation frequency in Hz.', required=True, default=1.0, minimum=0.001, unit='Hz'), ParamDef(name='amplitude', type='float', description='Peak amplitude of the sine wave.', default=1.0), ParamDef(name='offset', type='float', description='DC offset added to the sine wave.', default=0.0),), inputs=1, outputs=1, stateful=True, tags=('generator', 'periodic'), impl_key='transform.oscillator'),
    'proportional': TransformDef(kind='proportional', description='Proportional gain (P term). Multiplies input by gain factor.', params=(ParamDef(name='gain', type='float', description='Proportional gain factor (Kp).', default=1.0),), inputs=1, outputs=1, tags=('control', 'math'), impl_key='transform.proportional'),
    'pulse': TransformDef(kind='pulse', description='Generate periodic pulses. Input is ignored.', params=(ParamDef(name='interval_ms', type='float', description='Time between pulse starts in milliseconds.', required=True, default=1000.0, minimum=1.0, unit='ms'), ParamDef(name='duration_ms', type='float', description='Pulse duration in milliseconds.', required=True, default=100.0, minimum=1.0, unit='ms'), ParamDef(name='value', type='float', description='Output value during pulse (0 otherwise).', default=1.0),), inputs=1, outputs=1, stateful=True, tags=('generator', 'periodic'), impl_key='transform.pulse'),
    'pwm_duty': SinkDef(kind='pwm_duty', description='Drive a PWM duty-cycle command from a scalar signal.', params=(ParamDef(name='channel', type='int', description='Logical PWM channel identifier.', required=True, minimum=0),), inputs=1, requires=('pwm',), tags=('actuator',), impl_key='sink.pwm_duty'),
    'recall': TransformDef(kind='recall', description='Retrieve value from a named tap. Replaces current value with tap value.', params=(ParamDef(name='name', type='string', description='Name of the tap to recall from (must match a tap defined earlier in the slot).', required=True), ParamDef(name='fallback', type='float', description='Value to use if tap not found.', default=0.0),), inputs=1, outputs=1, tags=('routing', 'miso'), impl_key='transform.recall'),
    'scale': TransformDef(kind='scale', description='Multiply the input signal by a scalar factor.', params=(ParamDef(name='factor', type='float', description='Scalar multiplier applied to the input.', required=True, default=1.0),), inputs=1, outputs=1, tags=('math',), impl_key='transform.scale'),
    'servo_angle': SinkDef(kind='servo_angle', description='Drive a servo target angle in degrees.', params=(ParamDef(name='servo_id', type='int', description='Logical servo identifier.', required=True, minimum=0),), inputs=1, requires=('servo',), tags=('actuator',), impl_key='sink.servo_angle'),
    'slew_rate': TransformDef(kind='slew_rate', description='Limit how quickly the output is allowed to change, in output units per second.', params=(ParamDef(name='rate', type='float', description='Maximum absolute output change per second.', required=True, default=0.0, minimum=0.0, unit='units/s'),), inputs=1, outputs=1, stateful=True, tags=('stateful', 'limiter'), impl_key='transform.slew_rate'),
    'sum': TransformDef(kind='sum', description='Sum values from multiple named taps. Enables MISO (multiple-input, single-output) patterns like PID.', params=(ParamDef(name='inputs', type='string_list', description='List of tap names to sum together (max 4).', required=True),), inputs=0, outputs=1, tags=('routing', 'miso', 'math'), impl_key='transform.sum'),
    'tap': TransformDef(kind='tap', description='Store current value to a named tap for recall by other transforms. Passes value through unchanged.', params=(ParamDef(name='name', type='string', description='Name of the tap (max 11 chars). Used by recall/sum to reference this value.', required=True),), inputs=1, outputs=1, stateful=True, tags=('routing', 'miso'), impl_key='transform.tap'),
    'threshold': TransformDef(kind='threshold', description='Binary output based on cutoff value.', params=(ParamDef(name='cutoff', type='float', description='Threshold cutoff value.', required=True, default=0.5), ParamDef(name='output_low', type='float', description='Output value when input is below cutoff.', default=0.0), ParamDef(name='output_high', type='float', description='Output value when input is at or above cutoff.', default=1.0),), inputs=1, outputs=1, tags=('logic',), impl_key='transform.threshold'),
    'toggle': TransformDef(kind='toggle', description='Flip output state each time input crosses threshold (rising edge).', params=(ParamDef(name='threshold', type='float', description='Threshold for detecting rising edge.', default=0.5),), inputs=1, outputs=1, stateful=True, tags=('logic',), impl_key='transform.toggle'),
}

CONTROL_GRAPH_SPECS = {name: spec.to_dict() for name, spec in CONTROL_GRAPH_SPEC_OBJECTS.items()}
