# AUTO-GENERATED FILE — DO NOT EDIT BY HAND
# Generated from VERSION in schema.py

PROTOCOL_VERSION = 1
SCHEMA_VERSION = 1
CLIENT_VERSION = "1.0.0"
BOARD = "esp32"
NAME = "robot"
CAPABILITIES_MASK = 0x000F
