#!/usr/bin/env python3
"""
Generate Robot API class from command schema.

This generator creates a unified Python API class that provides:
- Lazy-loaded service properties for each category
- Connection management
- State/safety helpers

The generated API is the primary interface for Python users.

Usage:
    python -m mara_host.tools.gen_api
"""

from __future__ import annotations

import sys
from pathlib import Path
from datetime import datetime
from collections import defaultdict

# Add parent to path for imports
TOOLS_DIR = Path(__file__).parent
HOST_DIR = TOOLS_DIR.parent
sys.path.insert(0, str(HOST_DIR))
sys.path.insert(0, str(HOST_DIR.parent))

from mara_host.tools.schema.commands import COMMAND_OBJECTS
from mara_host.tools.schema.commands.core import CommandDef


# =============================================================================
# Output Paths
# =============================================================================

API_OUTPUT = HOST_DIR / "api" / "_generated_api.py"


# =============================================================================
# Code Generation Helpers
# =============================================================================

# Commands to skip (internal/protocol-level)
SKIP_COMMANDS = {
    "CMD_ACK", "CMD_NACK", "CMD_ERROR", "CMD_UNKNOWN",
    "CMD_HEARTBEAT",
}


def category_to_property_name(category: str) -> str:
    """Convert category to service property name."""
    # ctrl -> control, dc -> dc_motor, etc.
    renames = {
        "dc": "dc_motor",
        "ctrl": "control",
        "imu": "imu",
        "pwm": "pwm",
        "gpio": "gpio",
        "led": "led",
        "mcu": "mcu",
    }
    return renames.get(category, category)


def category_to_class_name(category: str) -> str:
    """Convert category to generated service class name."""
    return f"Generated{category.title().replace('_', '')}Service"


def group_commands_by_category() -> dict[str, list[tuple[str, CommandDef]]]:
    """Group commands by their category."""
    by_category: dict[str, list[tuple[str, CommandDef]]] = defaultdict(list)

    for cmd_name, cmd_def in COMMAND_OBJECTS.items():
        if cmd_name in SKIP_COMMANDS:
            continue
        if cmd_def.direction not in ("host->mcu", "both"):
            continue

        category = cmd_def.get_category(cmd_name)
        by_category[category].append((cmd_name, cmd_def))

    return dict(by_category)


def generate_api() -> str:
    """Generate the _generated_api.py content."""
    by_category = group_commands_by_category()

    lines = [f'''# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: tools/gen_api.py
# Generated at: {datetime.now().isoformat()}
"""
Generated Robot API class.

This provides a unified Python interface to the robot with lazy-loaded services.

Example:
    from mara_host.api import Robot

    async with Robot("/dev/ttyUSB0") as robot:
        await robot.connect()
        await robot.arm()
        await robot.activate()

        # Access services
        await robot.servo.attach(0, channel=13)
        await robot.servo.set_angle(0, 90)

        await robot.deactivate()
        await robot.disarm()
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from mara_host.command.client import MaraClient
    from mara_host.services._generated_services import (
''']

    # Add service imports in TYPE_CHECKING block
    for category in sorted(by_category.keys()):
        class_name = category_to_class_name(category)
        lines.append(f"        {class_name},\n")

    lines.append('''    )


class Robot:
    """
    Unified Python API for robot control.

    Provides lazy-loaded service properties for each command category.
    Services are instantiated on first access.

    Example:
        robot = Robot("/dev/ttyUSB0")
        await robot.connect()

        # Services are lazily loaded
        await robot.servo.set_angle(0, 90)
        await robot.dc_motor.set_speed(0, 0.5)
    """

    def __init__(self, port: str, baudrate: int = 115200):
        """
        Initialize the Robot API.

        Args:
            port: Serial port path (e.g., "/dev/ttyUSB0")
            baudrate: Serial baudrate (default 115200)
        """
        self._port = port
        self._baudrate = baudrate
        self._client: Optional["MaraClient"] = None

        # Lazy service caches
''')

    # Add service cache attributes
    for category in sorted(by_category.keys()):
        prop_name = category_to_property_name(category)
        class_name = category_to_class_name(category)
        lines.append(f'        self._{prop_name}_service: Optional["{class_name}"] = None\n')

    lines.append('''
    @property
    def client(self) -> "MaraClient":
        """Get the underlying client (raises if not connected)."""
        if self._client is None:
            raise RuntimeError("Not connected. Call connect() first.")
        return self._client

    @property
    def is_connected(self) -> bool:
        """Check if connected to the robot."""
        return self._client is not None and self._client.is_connected

    async def connect(self) -> None:
        """Connect to the robot."""
        from mara_host.command.client import MaraClient

        if self._client is not None:
            return  # Already connected

        self._client = MaraClient(self._port, self._baudrate)
        await self._client.connect()

    async def disconnect(self) -> None:
        """Disconnect from the robot."""
        if self._client is not None:
            await self._client.disconnect()
            self._client = None

    async def __aenter__(self) -> "Robot":
        """Async context manager entry."""
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None:
        """Async context manager exit."""
        await self.disconnect()

    # ==========================================================================
    # Safety Convenience Methods
    # ==========================================================================

    async def arm(self):
        """Arm the robot (enable motors)."""
        return await self.safety.arm()

    async def disarm(self):
        """Disarm the robot (disable motors)."""
        return await self.safety.disarm()

    async def activate(self):
        """Activate the robot (accept motion commands)."""
        return await self.safety.activate()

    async def deactivate(self):
        """Deactivate the robot (stop accepting motion)."""
        return await self.safety.deactivate()

    async def estop(self):
        """Emergency stop."""
        return await self.safety.estop()

    async def stop(self):
        """Soft stop all motion."""
        return await self.safety.stop()

''')

    # Generate service properties
    lines.append("    # ==========================================================================\n")
    lines.append("    # Service Properties (lazy-loaded)\n")
    lines.append("    # ==========================================================================\n\n")

    for category in sorted(by_category.keys()):
        prop_name = category_to_property_name(category)
        class_name = category_to_class_name(category)
        cmd_count = len(by_category[category])

        lines.append(f'''    @property
    def {prop_name}(self) -> "{class_name}":
        """
        {category.title()} service ({cmd_count} commands).

        Provides methods for {category}-related operations.
        """
        if self._{prop_name}_service is None:
            from mara_host.services._generated_services import {class_name}
            self._{prop_name}_service = {class_name}(self.client)
        return self._{prop_name}_service

''')

    # Add helper to get service by name
    lines.append('''
    def get_service(self, category: str):
        """
        Get a service by category name.

        Args:
            category: Service category (e.g., "servo", "dc_motor")

        Returns:
            The service instance, or None if not found
        """
        return getattr(self, category, None)

    def list_services(self) -> list[str]:
        """List available service categories."""
        return [
''')

    for category in sorted(by_category.keys()):
        prop_name = category_to_property_name(category)
        lines.append(f'            "{prop_name}",\n')

    lines.append('''        ]
''')

    return "".join(lines)


# =============================================================================
# Main
# =============================================================================

def main():
    print("Generating Robot API class...")

    by_category = group_commands_by_category()

    # Ensure output directory exists
    API_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    # Generate and write output
    content = generate_api()
    API_OUTPUT.write_text(content)

    print(f"  -> {API_OUTPUT}")
    print(f"Generated Robot class with {len(by_category)} service properties")


if __name__ == "__main__":
    main()
