#!/usr/bin/env python3
"""
Generate tooling backend registry from discovered backend packages.

This generator scans `services/tooling/backends/implementations/*/` for backend
packages and generates the auto-loading code for the registry.

Each backend package must have:
- __init__.py with a `register_backends(registry)` function

Usage:
    python -m mara_host.tools.gen_tooling_backends
"""

from __future__ import annotations

import ast
from datetime import datetime
from pathlib import Path


# =============================================================================
# Paths
# =============================================================================

TOOLS_DIR = Path(__file__).parent
HOST_DIR = TOOLS_DIR.parent
BACKENDS_DIR = HOST_DIR / "services" / "tooling" / "backends"
IMPLEMENTATIONS_DIR = BACKENDS_DIR / "implementations"
OUTPUT_FILE = BACKENDS_DIR / "_generated_loaders.py"


# =============================================================================
# Backend Discovery
# =============================================================================

def discover_backends() -> list[str]:
    """
    Discover backend packages under services/tooling/backends/implementations/.

    Returns list of package names (e.g., ["platformio", "cmake"]) that have
    a register_backends function in their __init__.py.
    """
    backends = []

    if not IMPLEMENTATIONS_DIR.exists():
        return backends

    for item in sorted(IMPLEMENTATIONS_DIR.iterdir()):
        if not item.is_dir():
            continue

        # Skip __pycache__ and private dirs
        if item.name.startswith("_") or item.name == "__pycache__":
            continue

        init_file = item / "__init__.py"
        if not init_file.exists():
            continue

        # Check if it has register_backends function
        if _has_register_function(init_file):
            backends.append(item.name)

    return backends


def _has_register_function(init_file: Path) -> bool:
    """Check if __init__.py exports a register_backends function."""
    try:
        source = init_file.read_text()
        tree = ast.parse(source)

        for node in ast.walk(tree):
            # Check for function definition
            if isinstance(node, ast.FunctionDef) and node.name == "register_backends":
                return True
            # Check for import (from .x import register_backends)
            if isinstance(node, ast.ImportFrom):
                for alias in node.names:
                    if alias.name == "register_backends" or alias.asname == "register_backends":
                        return True

        return False
    except Exception:
        return False


# =============================================================================
# Code Generation
# =============================================================================

def generate_loaders(backends: list[str]) -> str:
    """Generate the _generated_loaders.py content."""
    lines = [
        "# AUTO-GENERATED FILE - DO NOT EDIT",
        f"# Generated by: tools/gen_tooling_backends.py",
        f"# Generated at: {datetime.now().isoformat()}",
        '"""',
        "Auto-generated backend loaders.",
        "",
        "This module is imported by registry.py to auto-load all discovered backends.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import TYPE_CHECKING",
        "",
        "if TYPE_CHECKING:",
        "    from .registry import BackendRegistry",
        "",
        "",
        "# Discovered backends:",
    ]

    for name in backends:
        lines.append(f"#   - {name}")

    lines.append("")
    lines.append("")
    lines.append("def load_all_backends(registry: BackendRegistry) -> list[str]:")
    lines.append('    """Load all discovered backends into the registry.')
    lines.append("")
    lines.append("    Returns:")
    lines.append("        List of successfully loaded backend names.")
    lines.append('    """')
    lines.append("    loaded = []")
    lines.append("")

    for name in backends:
        lines.append(f"    # {name}")
        lines.append("    try:")
        lines.append(f"        from .implementations.{name} import register_backends as register_{name}")
        lines.append(f"        register_{name}(registry)")
        lines.append(f'        loaded.append("{name}")')
        lines.append("    except ImportError:")
        lines.append("        pass")
        lines.append("")

    lines.append("    return loaded")
    lines.append("")

    return "\n".join(lines)


# =============================================================================
# Main
# =============================================================================

def main():
    print("Generating tooling backend loaders...")

    backends = discover_backends()

    if not backends:
        print("  No backends found!")
        return

    print(f"  Discovered backends: {', '.join(backends)}")

    content = generate_loaders(backends)
    OUTPUT_FILE.write_text(content)
    print(f"  -> {OUTPUT_FILE}")

    print(f"Generated loader for {len(backends)} backends")


if __name__ == "__main__":
    main()
