#!/usr/bin/env python3
"""
Generate service base classes from command schema.

This generator reads:
- `mara_host/tools/schema/commands/` - Firmware command definitions

And produces:
- mara_host/services/_generated_services.py - Base service classes per category

Each generated service class provides:
1. Thin wrapper methods for each command in the category
2. ServiceResult return types for consistent error handling
3. Optional state tracking hooks

Manual services (like MotorService, ServoService) can extend or replace
these generated classes when they need additional business logic.

Usage:
    python -m mara_host.tools.gen_services
"""

from __future__ import annotations

import sys
from pathlib import Path
from datetime import datetime
from collections import defaultdict
from typing import Any

# Add parent to path for imports
TOOLS_DIR = Path(__file__).parent
HOST_DIR = TOOLS_DIR.parent
sys.path.insert(0, str(HOST_DIR))
sys.path.insert(0, str(HOST_DIR.parent))

from mara_host.tools.schema.commands import COMMAND_OBJECTS
from mara_host.tools.schema.commands.core import CommandDef, FieldDef, UNSET


# =============================================================================
# Output Paths
# =============================================================================

SERVICES_OUTPUT = HOST_DIR / "services" / "_generated_services.py"


# =============================================================================
# Code Generation Helpers
# =============================================================================

# Commands to skip (internal/protocol-level)
SKIP_COMMANDS = {
    "CMD_ACK", "CMD_NACK", "CMD_ERROR", "CMD_UNKNOWN",
    "CMD_HEARTBEAT",  # Infrastructure
}

# Python type mapping
SCHEMA_TO_PYTHON_TYPE = {
    "string": "str",
    "str": "str",
    "int": "int",
    "integer": "int",
    "float": "float",
    "number": "float",
    "bool": "bool",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
}


def field_to_python_type(field: FieldDef) -> str:
    """Convert FieldDef type to Python type hint."""
    base_type = SCHEMA_TO_PYTHON_TYPE.get(field.type, "Any")
    if field.default is not UNSET or not field.required:
        return f"{base_type} | None"
    return base_type


def field_to_default(field: FieldDef) -> str:
    """Get default value as Python literal."""
    if field.default is UNSET:
        if not field.required:
            return "None"
        return ""  # No default
    if isinstance(field.default, str):
        return repr(field.default)
    return repr(field.default)


def cmd_to_method_name(cmd_name: str, cmd_def: CommandDef) -> str:
    """Convert CMD_CATEGORY_ACTION to method name."""
    return cmd_def.get_method_name(cmd_name)


def category_to_class_name(category: str) -> str:
    """Convert category to class name."""
    # dc -> Dc, gpio -> Gpio, imu -> Imu
    return category.title().replace("_", "")


def generate_header() -> str:
    """Generate file header."""
    return f'''# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: tools/gen_services.py
# Generated at: {datetime.now().isoformat()}
"""
Generated base service classes from command schema.

These classes provide thin wrappers around firmware commands.
Manual services (MotorService, ServoService, etc.) can extend these
or replace them when additional business logic is needed.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from mara_host.core.result import ServiceResult

if TYPE_CHECKING:
    from mara_host.command.client import MaraClient


class GeneratedServiceBase:
    """Base class for generated services."""

    def __init__(self, client: "MaraClient"):
        self.client = client

'''


def generate_service_class(category: str, commands: list[tuple[str, CommandDef]]) -> str:
    """Generate a service class for a category of commands."""
    class_name = f"Generated{category_to_class_name(category)}Service"

    lines = [f'''
class {class_name}(GeneratedServiceBase):
    """
    Generated service for {category} commands.

    Provides thin wrapper methods around firmware commands.
    """

''']

    # Track method names to handle collisions
    method_counts: dict[str, int] = {}
    for cmd_name, cmd_def in commands:
        base_name = cmd_to_method_name(cmd_name, cmd_def)
        method_counts[base_name] = method_counts.get(base_name, 0) + 1

    used_methods: set[str] = set()

    for cmd_name, cmd_def in sorted(commands, key=lambda x: x[0]):
        base_method_name = cmd_to_method_name(cmd_name, cmd_def)

        # Handle collision: use full command name if duplicate
        if method_counts[base_method_name] > 1:
            # Use full command-derived name: CMD_GET_SAFETY_TIMEOUTS -> get_safety_timeouts
            method_name = cmd_name.removeprefix("CMD_").lower()
        else:
            method_name = base_method_name

        # Ensure uniqueness within this class
        if method_name in used_methods:
            method_name = cmd_name.removeprefix("CMD_").lower()
        used_methods.add(method_name)

        # Build method signature - required params first, then optional
        params = ["self"]
        doc_params = []
        payload_items = []

        # Separate required and optional fields
        required_fields = []
        optional_fields = []

        for field_name, field_def in cmd_def.payload.items():
            if not isinstance(field_def, FieldDef):
                continue
            if field_def.required and field_def.default is UNSET:
                required_fields.append((field_name, field_def))
            else:
                optional_fields.append((field_name, field_def))

        # Add required params first, then optional
        for field_name, field_def in required_fields + optional_fields:
            py_type = field_to_python_type(field_def)
            default = field_to_default(field_def)

            if default and not (field_def.required and field_def.default is UNSET):
                params.append(f"{field_name}: {py_type} = {default}")
            else:
                params.append(f"{field_name}: {py_type}")

            desc = field_def.description or field_name
            doc_params.append(f"            {field_name}: {desc}")
            payload_items.append(f'"{field_name}": {field_name}')

        params_str = ", ".join(params)
        payload_str = "{" + ", ".join(payload_items) + "}" if payload_items else "{}"

        # Generate docstring
        doc_params_str = "\n".join(doc_params) if doc_params else "            None"

        # Escape description for docstring
        description = cmd_def.description.replace('"', '\\"')

        lines.append(f'''    async def {method_name}({params_str}) -> ServiceResult:
        """
        {description}

        Args:
{doc_params_str}

        Returns:
            ServiceResult with success/failure
        """
        payload = {payload_str}
        ok, error, data = await self.client.send_with_data("{cmd_name}", payload)
        if ok:
            return ServiceResult.success(data=data)
        return ServiceResult.failure(error=error or "Command failed")

''')

    return "".join(lines)


def group_commands_by_category() -> dict[str, list[tuple[str, CommandDef]]]:
    """Group commands by their category."""
    by_category: dict[str, list[tuple[str, CommandDef]]] = defaultdict(list)

    for cmd_name, cmd_def in COMMAND_OBJECTS.items():
        if cmd_name in SKIP_COMMANDS:
            continue
        # Only include host->mcu commands
        if cmd_def.direction not in ("host->mcu", "both"):
            continue

        category = cmd_def.get_category(cmd_name)
        by_category[category].append((cmd_name, cmd_def))

    return dict(by_category)


def generate_registry(categories: list[str]) -> str:
    """Generate service registry."""
    lines = ['''
# =============================================================================
# Service Registry
# =============================================================================

GENERATED_SERVICES: dict[str, type[GeneratedServiceBase]] = {
''']

    for category in sorted(categories):
        class_name = f"Generated{category_to_class_name(category)}Service"
        lines.append(f'    "{category}": {class_name},\n')

    lines.append('''}


def get_generated_service(client: "MaraClient", category: str) -> GeneratedServiceBase | None:
    """Get a generated service instance by category."""
    service_class = GENERATED_SERVICES.get(category)
    if service_class:
        return service_class(client)
    return None


def list_categories() -> list[str]:
    """List all available service categories."""
    return list(GENERATED_SERVICES.keys())
''')

    return "".join(lines)


def generate_all() -> str:
    """Generate the complete _generated_services.py content."""
    lines = [generate_header()]

    # Group commands by category
    by_category = group_commands_by_category()

    # Generate service class for each category
    for category in sorted(by_category.keys()):
        commands = by_category[category]
        lines.append(generate_service_class(category, commands))

    # Generate registry
    lines.append(generate_registry(list(by_category.keys())))

    return "".join(lines)


# =============================================================================
# Main
# =============================================================================

def main():
    print("Generating service classes from command schema...")

    # Group commands
    by_category = group_commands_by_category()
    total_methods = sum(len(cmds) for cmds in by_category.values())

    # Generate output
    content = generate_all()
    SERVICES_OUTPUT.write_text(content)

    print(f"  -> {SERVICES_OUTPUT}")
    print(f"Generated {len(by_category)} service classes with {total_methods} methods")

    # Print summary
    for category in sorted(by_category.keys()):
        class_name = f"Generated{category_to_class_name(category)}Service"
        count = len(by_category[category])
        print(f"    {class_name}: {count} methods")


if __name__ == "__main__":
    main()
